### ISSUE TITLE
[BUG] cant install v2.5

### ISSUE THREAD

**Issue by Fabian1601** [AlexPresso/VideoStation-FFMPEG-Patcher#104]
Hello Alex,

i got an download error when trying to install.

----------------------------------------------------------------------------------------------------------------
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 54  9965   54  5455    0     0  11197      0 --:--:-- --:--:-- --:--:-- 11201
100  9965  100  9965    0     0  20190      0 --:--:-- --:--:-- --:--:-- 20172
[0;37m[2023-10-16 20:06:31] [0m[INFO] [0mffmpeg-patcher
[0;37m[2023-10-16 20:06:31] [0m[INFO] [0mDownloading motd... [0;31mError
[0;37m[2023-10-16 20:06:32] [0m[ERROR] [0;31mAn error occurred while downloading https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/Main/motd.txt. Rolling back changes...
[0;37m[2023-10-16 20:06:32] [0m[INFO] [0m====== Unpatch procedure ======
[0;37m[2023-10-16 20:06:32] [0m[INFO] [0mlibsynovte.so was not patched, keeping actual file.
[0;37m[2023-10-16 20:06:32] [0m[INFO] [0mRemove patch config.
[0;37m[2023-10-16 20:06:32] [0m[INFO] [0mRestarting CodecPack...
restart package [CodecPack] successfully
[0;37m[2023-10-16 20:06:40] [0m[INFO] [0mRestarting VideoStation...
restart package [VideoStation] successfully
[0;37m[2023-10-16 20:06:54] [0m[INFO] [0mCleaning orphan files...
[0;37m[2023-10-16 20:06:54] [0m[SUCCESS] [0;32mUnpatch complete
[0;37m[2023-10-16 20:06:54] [0m[ERROR] [0;31mAn error occurred while downloading https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/Main/motd.txt, every changes were rolled back.
[0;37m[2023-10-16 20:06:54] [0m[ERROR] [0;31mPlease check your internet connection / GithubStatus. If you think this is an error, please file an issue to the repository.

**Comment by AlexPresso** [comment]
Hi @Fabian1601 
Everything seems to work find on my side, could you please try again ? It could possibly be a Github issue

**Comment by Fabian1601** [comment]
Error is the still the same

**Comment by AlexPresso** [comment]
Which command are you using ? I noticed you're using `Main` branch but correct name is `main` (small "m")
