### ISSUE TITLE
[BUG] offline trancoding fail After 2.5

### ISSUE THREAD

**Issue by Fabian1601** [AlexPresso/VideoStation-FFMPEG-Patcher#105]
Hey Alex,

after the latest Update the offline transcoding fails everytime. Playback is Fine. 

https://gist.github.com/Fabian1601/b8ae614a42c24be7030ca1a8b8bb79de

**Comment by AlexPresso** [comment]
Hi @Fabian1601 

Sorry, I made a mistake in the wrapper that I didn't see while testing, could you try the following fix (#106) please:

- uninstall the patch : `curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/fix_err_code/patcher.sh | bash -s -- -a unpatch`
- install the new patch `curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/fix_err_code/patcher.sh | bash -s -- -a patch -b fix_pixfmt`

If you still have an issue please run the issue-report tool and post the result here again

**Comment by Fabian1601** [comment]
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  9965  100  9965    0     0  18044      0 --:--:-- --:--:-- --:--:-- 18052
[0;37m[2023-10-23 21:45:54] [0m[INFO] [0mffmpeg-patcher
[0;37m[2023-10-23 21:45:54] [0m[INFO] [0mDownloading motd... [0;31mError
[0;37m[2023-10-23 21:45:54] [0m[ERROR] [0;31mAn error occurred while downloading https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/fix_pixfmt/motd.txt. Rolling back changes...
[0;37m[2023-10-23 21:45:54] [0m[INFO] [0m====== Unpatch procedure ======
[0;37m[2023-10-23 21:45:54] [0m[INFO] [0mlibsynovte.so was not patched, keeping actual file.
[0;37m[2023-10-23 21:45:54] [0m[INFO] [0mRemove patch config.
[0;37m[2023-10-23 21:45:54] [0m[INFO] [0mRestarting CodecPack...
restart package [CodecPack] successfully
[0;37m[2023-10-23 21:46:01] [0m[INFO] [0mRestarting VideoStation...
restart package [VideoStation] successfully
[0;37m[2023-10-23 21:46:15] [0m[INFO] [0mCleaning orphan files...
[0;37m[2023-10-23 21:46:15] [0m[SUCCESS] [0;32mUnpatch complete
[0;37m[2023-10-23 21:46:15] [0m[ERROR] [0;31mAn error occurred while downloading https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/fix_pixfmt/motd.txt, every changes were rolled back.
[0;37m[2023-10-23 21:46:15] [0m[ERROR] [0;31mPlease check your internet connection / GithubStatus. If you think this is an error, please file an issue to the repository.

**Comment by AlexPresso** [comment]
Sorry, I updated the comment with the right comment but you were too fast ahah the correct one is with `fix_err_code` : 

curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/fix_err_code/patcher.sh | bash -s -- -a patch -b fix_err_code

**Comment by Fabian1601** [comment]
Hello Alex,

everything works fine 👍
Thanks

**Comment by mperathoner** [comment]
Hi Alex, I tried this all. It ends with "bash
![GitHub](https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/assets/155825224/9cf9520a-c5fc-4390-a427-ae3c88b914f4)

**Comment by AlexPresso** [comment]
Hi :) 
It's because this branch doesn't exist anymore, please follow the command from the repository home page (main branch)
