### ISSUE TITLE
[BUG] can't update with 2.6 from 2.0

### ISSUE THREAD

**Issue by zouc2000** [AlexPresso/VideoStation-FFMPEG-Patcher#110]
I can't update 2.6 from a version 2.0:

- Clean re-install VS + Advanced Multimedia Extensions
- Applied patch successfully
- Played successfully on PC with VS 

Can't play on my iPhone video which could be played before (eg. hvec/eac3 videos) with version 2.0

### 2.6 install

[2023-11-13 23:22:16] [INFO] ffmpeg-patcher
[2023-11-13 23:22:16] [INFO] Downloading motd... Done
[2023-11-13 23:22:16] [Message of the day]

A new version of the wrapper was deployed (v2.6) fixing an issue with offline transcoding.
You can find the changelog here: https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/releases/tag/2.6

/!\ PLEASE FOLLOW THE UPDATE PROCEDURE IN THE CHANGELOG TO UPDATE /!\

As always, please let me know of any issue you could have.

[2023-11-13 23:22:19] [INFO] You're running DSM 7.2 64570-3
[2023-11-13 23:22:19] [INFO] Tuned script for DSM 7.2 64570-3
[2023-11-13 23:22:19] [INFO] ====== Patching procedure (branch: main) ======
[2023-11-13 23:22:19] [INFO] Saving current ffmpeg as ffmpeg.orig
[2023-11-13 23:22:19] [INFO] Downloading ffmpeg.sh... Done
[2023-11-13 23:22:20] [INFO] Patching CodecPack's ffmpeg41
[2023-11-13 23:22:20] [INFO] Downloading ffmpeg41.sh... Done
[2023-11-13 23:22:20] [INFO] Downloading CodecPack's patch_config.sh... Done
[2023-11-13 23:22:20] [INFO] Downloading CodecPack's patch_utils.sh... Done
[2023-11-13 23:22:20] [INFO] Setting CodecPack's ffmpeg version to: ffmpeg
[2023-11-13 23:22:20] [INFO] Downloading VideoStation's patch_config.sh... Done
[2023-11-13 23:22:20] [INFO] Downloading VideoStation's patch_utils.sh... Done
[2023-11-13 23:22:20] [INFO] Setting ffmpeg version to: ffmpeg
[2023-11-13 23:22:20] [INFO] Saving current libsynovte.so as libsynovte.so.orig
[2023-11-13 23:22:20] [INFO] Enabling eac3, dts and truehd
[2023-11-13 23:22:20] [INFO] Restarting CodecPack...
restart package [CodecPack] successfully
[2023-11-13 23:22:26] [INFO] Restarting VideoStation...
restart package [VideoStation] successfully
[2023-11-13 23:22:38] [INFO] Cleaning orphan files...
[2023-11-13 23:22:38] [SUCCESS] Done patching, you can now enjoy your movies ;) (please add a star to the repo if it worked for you)

### issue report

./issue-report.sh: line 11: /var/packages/VideoStation/patch_config.sh: No such file or directory
No patch_config.sh
libva info: VA-API version 1.18.0
libva info: Trying to open /var/packages/ffmpeg/target/lib/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_18
libva info: va_openDriver() returns 0

================ ISSUE REPORT TOOL ================
https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher

System Details.....................................
  DSM Version: 7.2 64570-3
  Arch details: Linux diskstation 4.4.302+ #64570 SMP Thu Jul 20 00:06:38 CST 2023 x86_64 GNU/Linux synology_geminilake_920+

Package Details....................................
  VideoStation version: 3.1.0-3153
  FFMPEG version (ffmpeg): 4.4.4-49
  CodecPack version: 3.1.0-3005

Patch Details......................................
  Is patched ? yes
  Has gstreamer ? no
FFMPEG VAAPI.......................................
  Trying display: drm
vainfo: VA-API version: 1.18 (libva 2.18.1)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 23.1.6 (3359d2df)
vainfo: Supported profile and entrypoints
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileNone                   : VAEntrypointStats
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointFEI
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointFEI
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointFEI
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileVP8Version0_3          : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointFEI
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSlice
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD

CodecPack Details..................................
  Has AAC ? yes
  Has HEVC ? yes

CodecPack target/bin content.......................
total 60
lrwxrwxrwx 1 CodecPack CodecPack    30 Mar 14  2023 ffmpeg33-for-audio -> ../pack/bin/ffmpeg33-for-audio
lrwxrwxrwx 1 CodecPack CodecPack    37 Mar 14  2023 ffmpeg33-for-surveillance -> ../pack/bin/ffmpeg33-for-surveillance
lrwxrwxrwx 1 CodecPack CodecPack    20 Mar 14  2023 ffmpeg41 -> ../pack/bin/ffmpeg41
-rwxr-xr-x 1 CodecPack CodecPack 46201 Mar 14  2023 synocodectool
CodecPack target/pack/bin content..................
total 1084
-rwxr-xr-x 1 root root 267312 Mar 24  2023 ffmpeg33-for-audio
-rwxr-xr-x 1 root root 267304 Mar 24  2023 ffmpeg33-for-surveillance
-rwsr-x--- 1 root root   1494 Nov 13 23:22 ffmpeg41
-rwxr-xr-x 1 root root 271320 Mar 24  2023 ffmpeg41-for-synoface
-rwxr-xr-x 1 root root 271320 Mar 24  2023 ffmpeg41.orig
-rwxr-xr-x 1 root root  14832 Mar 24  2023 vainfo

CodecPack status...................................
cat: /var/packages/CodecPack/var/codec_requirements.json: No such file or directory
file not exists

GSTInspect last stderr logs........................
tail: cannot open '/tmp/gstinspect*.stderr' for reading: No such file or directory

GSTInspect stderr.prev logs........................
cat: '/tmp/gstinspect*.stderr.prev': No such file or directory

GSTLaunch last stderr logs.........................
tail: cannot open '/tmp/gstlaunch*.stderr' for reading: No such file or directory

GSTLaunch stderr.prev logs.........................
cat: '/tmp/gstlaunch*.stderr.prev': No such file or directory

FFMPEG head logs...................................
head: cannot open '/tmp/ffmpeg*.stderr' for reading: No such file or directory

FFMPEG last stderr logs............................
tail: cannot open '/tmp/ffmpeg*.stderr' for reading: No such file or directory

FFMPEG prev logs...................................
cat: '/tmp/ffmpeg*.stderr.prev': No such file or directory

**Comment by AlexPresso** [comment]
Hi,
I'm not sure to understand what you mean by "can't update to 2.6" something went wrong during update? 

Or you mean the video is not working from your iphone after update ?

**Comment by zouc2000** [comment]
#2, the video is not working from my iphone after update
Patching with 2.6 showed only green/"Done" statuses

**Comment by AlexPresso** [comment]
Could you also connect to your NAS using SSH, run the following command and give me the output please: `realpath --version`

**Comment by zouc2000** [comment]
- Is the same video working using the web version of VideoStation ?  **Yes**
- What are the video and audio codecs of the media file you're trying to play ? **hvec/eac3** or **h264/eac3**
- What's your iPhone model name and which video player are you using to play the video ? **iPhone13 mini/ios16.6.1, iPhone builtin player**
- Are you 100% sure, it was working on your iPhone using the v2.6 ? **I'm sure it was working with 2.0 until recently when my iPhone failed reading videos, even ones I could read before. I therefore went for an update to try to recover the service**

NB: Video Station and AME have the auto-install set

realpath (GNU coreutils) **8.30**

**Comment by AlexPresso** [comment]
Thanks for your feedback

Did you receive an update of the VideoStation iPhone app before it stopped working ?

It's very strange because if it was an issue with the wrapper, you would have the same issue when trying to play the videos using the web version.
It should not be the case, but I suspect the iPhone VideoStation's app is no longer using the NAS to transcode but directly gets the video buffer and transcodes it on your iPhone,, but it would make no sense for the app to work like this on a mobile device as it is consuming way more data...

I don't think it will change anything to your problem, but by any chance, could you try the following hotfix (#111 ):
- uninstall the patch : `curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/main/patcher.sh | bash -s -- -a unpatch`
- install the new patch `curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/main/patcher.sh | bash -s -- -a patch -b fix_config_and_logs`

**Comment by zouc2000** [comment]
> -a patch -b fix_config_and_logs

Done, but with no more luck

> > I'm sure it was working with 2.0 until recently when my iPhone failed reading videos, even ones I could read before. I therefore went for an update to try to recover the service
> 
> You mean it was working fine with the 2.0 wrapper and then just stopped working without changing anything about the wrapper and/or VideoStation ?

Yes, that's it

I tried to uninstall VS on DS and DS Video on my iPhone without success in reading videos ...

**Comment by AlexPresso** [comment]
Okay, so I'm sorry to tell you that the wrapper is not the cause of your issue :(
It's possible DS Video app on your iPhone is no longer using your NAS to transcode the video after an update, probably [this one](https://apps.apple.com/fr/app/ds-video/id540949418):

```
3.4.34 | sept. 2019
Fixed the issue where there might be problems downloading MP4 files
```

It could also be something else, but I'm sure about something based on the issue-report you provided: `ffmpeg` is not called on your NAS, otherwise there would be some logs in the issue-report.

I'm sorry but I can't do anything about it

**Comment by zouc2000** [comment]
ok thanks anyway for searching, I'll investigate on my side to see what I can find.

**Comment by zouc2000** [comment]
Ok, found out the issue !

My nas was sending back a `400 The plain HTTP request was sent to HTTPS port` due to a mis-redirection of port 5000 to port internal 5001 in my router. My bad.

It was not a problem until recently and definitely not something linked to the patcher.

It works great now !

**Comment by AlexPresso** [comment]
Aaah no worries, I'm glad if everything is working again :)
