### ISSUE TITLE
Unsupported format

### ISSUE THREAD

**Issue by SayonaRRRa** [AlexPresso/VideoStation-FFMPEG-Patcher#115]
![image](https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/assets/33625430/3bf6710e-0e3f-44e5-8e6d-5ee1f8340aaa)

This is what i'm getting when I try to play this type of content. With a different type it works properly I'm guessing its because its encoded with h.265.
 h.264 works fine

**Comment by AlexPresso** [comment]
Hi,
You need to install Advanced Media Extensions (as said in the error message) to be able to transcode H.265 files. Also, you will have to unpatch and repatch after installing Advanced Media Extensions, as it also needs to be patched for VideoStation to be fully working.

**Comment by SayonaRRRa** [comment]
> Hi, You need to install Advanced Media Extensions (as said in the error message) to be able to transcode H.265 files. Also, you will have to unpatch and repatch after installing Advanced Media Extensions, as it also needs to be patched for VideoStation to be fully working.

Thank you for your advice. Yes, activating AME was the issue. Consider this matter solved.
