### ISSUE TITLE
Successfully patched. But DTS videos not playing through Video Center in browser.

### ISSUE THREAD

**Issue by selvasateesh** [AlexPresso/VideoStation-FFMPEG-Patcher#119]
Hello,
Originally, I tried to follow the steps listed in the following articles and it didn't work for playing DTS videos in the browser through video station 
1) (this link has bee redacted for moderation purposes ; it's a cracker, not a patcher and put you NAS against the Synology TOS)
2) https://github.com/SynoCommunity/spksrc/wiki/FAQ-FFmpeg

Then I came across this wrapper and followed the steps still facing the same issue. Could you help how to verify if the patch is proper in the directories? 

I am giving all relevant information below:

**Dependencies:**
<img width="824" alt="image" src="https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/assets/155258824/fba20ff5-5103-4850-bf6d-8c7b3d93890b">
<img width="231" alt="image" src="https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/assets/155258824/4f44c2b6-325a-4e8b-957e-081f318e6823">
<img width="236" alt="image" src="https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/assets/155258824/3796463b-4f4e-479b-85fe-feb951c1c40d">
<img width="294" alt="image" src="https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/assets/155258824/c7e215be-0329-4620-9c21-b8f0de520312">
<img width="337" alt="image" src="https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/assets/155258824/d55bf222-71fa-44f1-9410-ee6ef377284d">
<img width="718" alt="image" src="https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/assets/155258824/b7be2ae7-3f03-4f94-b09e-7888e53ad7ec">

**Media info:**
HEVC with 6 channel DTS audio
<img width="343" alt="image" src="https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/assets/155258824/12e94651-f144-4525-bc14-e399926981ad">

<img width="390" alt="image" src="https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/assets/155258824/8b100583-4b99-4c59-85bf-2f53af79039d">

**Unpatch:**
`root@DiskStation:~# curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/main/patcher.sh | bash -s -- -a unpatch -v 6
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10296  100 10296    0     0  39732      0 --:--:-- --:--:-- --:--:-- 39906
[2023-12-31 19:00:16] [INFO] ffmpeg-patcher
[2023-12-31 19:00:16] [INFO] Downloading motd... Done
[2023-12-31 19:00:16] [Message of the day]

A new version of the wrapper was deployed (v2.6) fixing an issue with offline transcoding.
You can find the changelog here: https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/releases/tag/2.6

/!\ PLEASE FOLLOW THE UPDATE PROCEDURE IN THE CHANGELOG TO UPDATE /!\

As always, please let me know of any issue you could have.

[2023-12-31 19:00:19] [INFO] You're running DSM 7.2.1 69057-3
[2023-12-31 19:00:19] [INFO] Tuned script for DSM 7.2.1 69057-3
[2023-12-31 19:00:19] [INFO] ====== Unpatch procedure ======
[2023-12-31 19:00:19] [INFO] Restoring libsynovte.so
[2023-12-31 19:00:19] [INFO] Restoring VideoStation's /var/packages/VideoStation/target/bin/ffmpeg.orig
[2023-12-31 19:00:19] [INFO] Restoring CodecPack's ffmpeg41
[2023-12-31 19:00:19] [INFO] Restarting CodecPack...
restart package [CodecPack] successfully
[2023-12-31 19:00:32] [INFO] Restarting VideoStation...
restart package [VideoStation] successfully
[2023-12-31 19:00:55] [SUCCESS] Unpatch complete
root@DiskStation:~#`

**Patch:**
`root@DiskStation:~# curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/main/patcher.sh | bash -s -- -v 6
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10296  100 10296    0     0  22596      0 --:--:-- --:--:-- --:--:-- 22678
[2023-12-31 19:02:35] [INFO] ffmpeg-patcher
[2023-12-31 19:02:35] [INFO] Downloading motd... Done
[2023-12-31 19:02:35] [Message of the day]

A new version of the wrapper was deployed (v2.6) fixing an issue with offline transcoding.
You can find the changelog here: https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/releases/tag/2.6

/!\ PLEASE FOLLOW THE UPDATE PROCEDURE IN THE CHANGELOG TO UPDATE /!\

As always, please let me know of any issue you could have.

[2023-12-31 19:02:38] [INFO] You're running DSM 7.2.1 69057-3
[2023-12-31 19:02:38] [INFO] Tuned script for DSM 7.2.1 69057-3
[2023-12-31 19:02:38] [INFO] ====== Patching procedure (branch: main) ======
[2023-12-31 19:02:38] [INFO] Saving current ffmpeg as ffmpeg.orig
[2023-12-31 19:02:38] [INFO] Downloading ffmpeg.sh... Done
[2023-12-31 19:02:39] [INFO] Patching CodecPack's ffmpeg41
[2023-12-31 19:02:39] [INFO] Downloading ffmpeg41.sh... Done
[2023-12-31 19:02:39] [INFO] Saving current libsynovte.so as libsynovte.so.orig
[2023-12-31 19:02:39] [INFO] Enabling eac3, dts and truehd
[2023-12-31 19:02:39] [INFO] Restarting CodecPack...
restart package [CodecPack] successfully
[2023-12-31 19:02:57] [INFO] Restarting VideoStation...
restart package [VideoStation] successfully
[2023-12-31 19:03:40] [INFO] Cleaning orphan files...
[2023-12-31 19:03:40] [SUCCESS] Done patching, you can now enjoy your movies ;) (please add a star to the repo if it worked for you)`

**Comment by AlexPresso** [comment]
It's first time I see this error message, but it looks like a VideoStation error

Could you please follow the procedure in issue template to give the issue report, so I can check what happens

**Comment by selvasateesh** [comment]
Here is the issue report output

`root@DiskStation:~# curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/main/issue-report.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2797  100  2797    0     0   5063      0 --:--:-- --:--:-- --:--:--  5076
bash: line 56: /var/packages/ffmpeg/target/bin/vainfo: No such file or directory

================ ISSUE REPORT TOOL ================
https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher

System Details.....................................
  DSM Version: 7.2.1 69057-3
  Arch details: Linux DiskStation 3.10.108 #69057 SMP Sat Sep 23 21:44:24 CST 2023 armv7l GNU/Linux synology_armada38x_ds218j

Package Details....................................
  VideoStation version: 3.1.1-3168
  FFMPEG version (ffmpeg): 6.0-2
  CodecPack version: 3.1.0-3005

Patch Details......................................
  Is patched ? yes
  Has gstreamer ? no

FFMPEG VAAPI.......................................
  No VAAPI Support

CodecPack Details..................................
  Has AAC ? no
  Has HEVC ? yes

CodecPack target/bin content.......................
total 36
lrwxrwxrwx 1 CodecPack CodecPack    30 Mar 14  2023 ffmpeg33-for-audio -> ../pack/bin/ffmpeg33-for-audio
lrwxrwxrwx 1 CodecPack CodecPack    37 Mar 14  2023 ffmpeg33-for-surveillance -> ../pack/bin/ffmpeg33-for-surveillance
lrwxrwxrwx 1 CodecPack CodecPack    20 Mar 14  2023 ffmpeg41 -> ../pack/bin/ffmpeg41
-rwxr-xr-x 1 CodecPack CodecPack 33418 Mar 14  2023 synocodectool

CodecPack target/pack/bin content..................
total 476
-rwxr-xr-x 1 root root 236792 Mar 23  2023 ffmpeg33-for-surveillance
-rwsr-x--- 1 root root   2519 Dec 31 19:02 ffmpeg41
-rwxr-xr-x 1 root root 244968 Mar 23  2023 ffmpeg41.orig

CodecPack status...................................
cat: /var/packages/CodecPack/var/codec_requirements.json: No such file or directory
file not exists


GSTInspect last stderr logs........................
tail: cannot open '/tmp/gstinspect*.stderr' for reading: No such file or directory

GSTInspect stderr.prev logs........................
cat: '/tmp/gstinspect*.stderr.prev': No such file or directory

GSTLaunch last stderr logs.........................
tail: cannot open '/tmp/gstlaunch*.stderr' for reading: No such file or directory

GSTLaunch stderr.prev logs.........................
cat: '/tmp/gstlaunch*.stderr.prev': No such file or directory

FFMPEG head logs...................................
head: cannot open '/tmp/ffmpeg*.stderr' for reading: No such file or directory

FFMPEG last stderr logs............................
tail: cannot open '/tmp/ffmpeg*.stderr' for reading: No such file or directory

FFMPEG prev logs...................................
cat: '/tmp/ffmpeg*.stderr.prev': No such file or directory

root@DiskStation:~#`

**Comment by AlexPresso** [comment]
Hi,
Thank you for the feedback, did you uninstall/reinstall VideoStation and Advanced Media Extensions before installing my patcher ?

The other patchers are conflicting with mine, first step would be to be shure your VideoStation's and Advanced Media Extension's installations are clean, by removing and reinstalling the packages

**Comment by AlexPresso** [comment]
I checked the Synology documentation about this error and it looks like your NAS is from "group 2": https://kb.synology.com/fr-fr/DSM/tutorial/Can_my_Synology_NAS_convert_videos_for_my_device

It means some format are not transcoded and you need to install a plugin in your browser or a Windows app, I have no idea which one, but as it's not an issue related to the wrapper, you'll have to ask the Synology support about it

**Comment by selvasateesh** [comment]
> Hi, Thank you for the feedback, did you uninstall/reinstall VideoStation and Advanced Media Extensions before installing my patcher ?
> 
> The other patchers are conflicting with mine, first step would be to be shure your VideoStation's and Advanced Media Extension's installations are clean, by removing and reinstalling the packages

I did that. Let me do again. Can you please confirm the following in this order?

1. Videostation uninstall and reinstall
2.  AME uninstall and reinstall
3. ffmpeg6 uninstall and reinstall
4. Reindex all media files from scratch for video station

**Comment by AlexPresso** [comment]
Hi,
It's perfect, but you don't need to delete the video station libeary so you don't need to reindex after :)

**Comment by selvasateesh** [comment]
I did all of the above steps. Still the same result

**Comment by AlexPresso** [comment]
Okay, so yoy will have to contact the Synology support to ask them wich plugin you have to install on your computer

It's not an issue with the wrapper, as described in the documentation, your nas is from group 2 and needs you to install a plugin on your computer : https://kb.synology.com/fr-fr/DSM/tutorial/Can_my_Synology_NAS_convert_videos_for_my_device

**Comment by selvasateesh** [comment]
Ok, let me check with Synology
