### ISSUE TITLE
[BUG] Video station use ffmpeg.orig 

### ISSUE THREAD

**Issue by Hoax017** [AlexPresso/VideoStation-FFMPEG-Patcher#12]
**System details**
- Synology model: DS1618+
- DSM version: DSM 7.0-41890
- VideoStation version: 3.0.1-2067
- Advanced Media Extensions version: 1.1.1-0202

**Describe the bug**
Video station use ffmpeg.orig ...

![image](https://user-images.githubusercontent.com/8215575/131408094-b4c39622-9b26-4754-aac8-49af042615f4.png)

**Comment by AlexPresso** [comment]
You forgot to give a name to your issue.
Also, all of this is purely intended, the [ffmpeg-wrapper.sh](https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/blob/main/ffmpeg-wrapper.sh#L27) first tries to decode with the `ffmpeg.orig` (`$bin1`) and switches to SynoCommunity ffmpeg (`$bin2`) if it fails.
