### ISSUE TITLE
[QA] Download motd.txt error

### ISSUE THREAD

**Issue by lqxxwx** [AlexPresso/VideoStation-FFMPEG-Patcher#120]
![Snipaste_2024-01-03_23-29-23](https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/assets/42995737/730114b2-3708-443b-81aa-c5c5920087e6)
But my internet works fine.

**Comment by AlexPresso** [comment]
Hi, 
Sometimes this issue happens when there is a  micro downtime on GH.
Did you try to rerun the patcher ?

**Comment by AlexPresso** [comment]
https://www.githubstatus.com/

**Comment by AlexPresso** [comment]
Hi,
Other users seems not to have any issue like this, are you behind any kind of firewall that could block the request ?
Also, if you are from China, you should probably use a proxy to make it work, the `proxy` tag is made for this usage:

`curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/main/patcher.sh | bash -s -- -p http://your-proxy`

**Comment by lqxxwx** [comment]
My router used a proxy.

> Hi, Other users seems not to have any issue like this, are you behind any kind of firewall that could block the request ? Also, if you are from China, you should probably use a proxy to make it work, the `proxy` tag is made for this usage:
> 
> `curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/main/patcher.sh | bash -s -- -p http://your-proxy`

My router used a proxy.
I Download to local，and run successfully.
Thanks.
