### ISSUE TITLE
[BUG] failure writing output to destination

### ISSUE THREAD

**Issue by Fabian1601** [AlexPresso/VideoStation-FFMPEG-Patcher#121]
Hello Alex,
After updating to the latest VS Version i can‘t install the Patch. 

https://gist.github.com/Fabian1601/7736d4273710fadf1b7475525

**Comment by AlexPresso** [comment]
Hi Fabian,
There may be an issue with GitHub right now, but I can't see your gist

**Comment by Fabian1601** [comment]
everything works fine now :-)
