### ISSUE TITLE
[QA] Error on patching ffmpeg

### ISSUE THREAD

**Issue by hutkayl** [AlexPresso/VideoStation-FFMPEG-Patcher#122]
Please check the [FAQ](https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/wiki/FAQ) before posting any question.

**Question**

Hi There,
I've got this error message. I tried to reinstall the ffmpeg package, but it didn't solve it. Do you have any idea what is the problem?
Thanx, HuL

![Képernyőkép – 2024-01-06 21-53-36](https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/assets/74777291/8612c61c-d54c-43cb-8df0-432a219f0587)

**Comment by Fabian1601** [comment]
Hi,
Remove „v -6“ from your code and everything will be Fine :)

**Comment by hutkayl** [comment]
> Hi, Remove „-v 6“ from your code and everything will be Fine :)

Are you sure? I use ffmpeg 6 not the default.

**Comment by Fabian1601** [comment]
I have all versions installed (4/5/6). 
so im not 100% sure. 
install ffmpeg 4 and than it will work :)

**Comment by hutkayl** [comment]
> I have all versions installed (4/5/6). so im not 100% sure. install ffmpeg 4 and than it will work :)

Okey! It was my fault! I forget the "-s --" before -v 6. Now it's successfully run the patch. 
Thanks!

**Comment by hutkayl** [comment]
I was an idiot...

**Comment by AlexPresso** [comment]
Hi,
No worries ;) I'm glad everything working now.

I just wanted to comment about this part :
> I have all versions installed (4/5/6).
so im not 100% sure.

 By default the patcher always use ffmpeg 4, even if you have other versions installed; So yes, if you want to use ffmpeg 6, you have to force it like you did, using the CLI parameter
