### ISSUE TITLE
[BUG] No sound on at least two movies

### ISSUE THREAD

**Issue by KidWar75** [AlexPresso/VideoStation-FFMPEG-Patcher#124]
**Provide System Details**
https://gist.github.com/KidWar75/72dbf8a3fdec3ce332f67a145c814f3e
VideoStation 3.1.1-3168
FFMpeg 4 & FFmpeg 6 installed
Advanced Media Extensions 3.1.0-3005

**Describe the bug**
I launch the movie Argylle & Napoleon and there is no sound on those two movies.
Similarities on those two film : DDP5.1.Atmos

**Additional context**
Here are the details for the two movies (mediainfo)

NAPOLEON :
Audio
ID                                       : 2
Format                                   : E-AC-3 JOC
Format/Info                              : Enhanced AC-3 with Joint Object Coding
Commercial name                          : Dolby Digital Plus with Dolby Atmos
Codec ID                                 : A_EAC3
Duration                                 : 2 h 37 min
Bit rate mode                            : Constant
Bit rate                                 : 768 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Delay relative to video                  : 24 s 169 ms
Stream size                              : 866 MiB (8%)
Language                                 : English
Service kind                             : Complete Main
Default                                  : Yes
Forced                                   : No
Complexity index                         : 16
Number of dynamic objects                : 15
Bed channel count                        : 1 channel
Bed channel configuration                : LFE

ARGYLLE : 
Audio
ID                                       : 2
Format                                   : E-AC-3 JOC
Format/Info                              : Enhanced AC-3 with Joint Object Coding
Commercial name                          : Dolby Digital Plus with Dolby Atmos
Codec ID                                 : A_EAC3
Duration                                 : 2 h 18 min
Bit rate mode                            : Constant
Bit rate                                 : 768 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Delay relative to video                  : 17 s 329 ms
Stream size                              : 762 MiB (8%)
Language                                 : English
Service kind                             : Complete Main
Default                                  : Yes
Forced                                   : No
Complexity index                         : 16
Number of dynamic objects                : 15
Bed channel count                        : 1 channel
Bed channel configuration                : LFE

**Comment by KidWar75** [comment]
FYI, I unistalled & reinstalled VideoStation & Advanced Media Extensions. Repatched VideoStation. Nothing changed.
However, while patching it said that a new version of the patcher v2.6 was out. Could it be the issue ?

**Comment by AlexPresso** [comment]
Hi KidWar75,

The new version available message is normal, it's displaying the same message for everyone even if you have latest version

The issue-report looks a bit cutted near the ffmpeg args (maybe copy paste didn't copy long lines), could you please resend the full report please ? :)

**Comment by KidWar75** [comment]
> Hi KidWar75,
> 
> The new version available message is normal, it's displaying the same message for everyone even if you have latest version
> 
> The issue-report looks a bit cutted near the ffmpeg args (maybe copy paste didn't copy long lines), could you please resend the full report please ? :)

Here you go ! :
https://gist.github.com/KidWar75/df511cb209e42c8df9df524baacea8c3

**Comment by AlexPresso** [comment]
Thank you,
Does it work with other EAC3 / DTS movies ?

The smartphone and TV app is not supposed to work with these codecs so I guess the problem is because I force the use of lib_aac when lib_mp3lame is working fine

**Comment by KidWar75** [comment]
Just tried with : 

- Tokyo.Vice.S02E06.I.Choose.You.1080p.AMZN.WEB-DL.DDP5.1.Atmos.H.264-FLUX which is EAC3 -> no problem.
- The.Fighter.2010.BluRay.1080p.x264.DTS.dxva-xander which is DTS -> No problem

**Comment by AlexPresso** [comment]
Okay I will make some tests and get back to you :)

**Comment by KidWar75** [comment]
> Okay I will make some tests and get back to you :)

Cheers buddy and thx again for your work! :)

**Comment by AlexPresso** [comment]
Hi @KidWar75 

Looks like the codec of your videos is not "vanilla" `eac3`, it's `eac3_joc` and it looks like it's not included in the ffmpeg version we're using (ffmpeg4), I tried on my NAS to run the following and it doesn't return any encoder / decoder support : `ffmpeg -codecs | grep eac3_joc`

**Comment by KidWar75** [comment]
Hey!
Cheers for the answer.
Ye Vanilla eac3 is working fine, no worries on that end.

**Comment by AlexPresso** [comment]
Hi Kidwar75,

By chance, have you tried with other ffmpeg versions ? like ffmpeg5 or ffmpeg6, I have no idea if it will work or not but it could be nice to give it a try

**Comment by KidWar75** [comment]
How do I do that ?
I'm a noob really, I just follow your steps and that's it ^^

**Comment by AlexPresso** [comment]
No worries :)
You can try it by:
- installing ffmpeg5 and/or ffmpeg6 from the Synology Packages Manager
- unpatch current version: `curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/main/patcher.sh | bash -s -- -a unpatch`
- patch again specifying ffmpeg version to use (i.e ffmpeg5) : `curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/main/patcher.sh | bash -s -- -v 5`

This example is for ffmpeg5, if you want to give it a try with ffmpeg6 or go back to ffmpeg4, you have to repeat the previous steps :)

PS: please note that using ffmpeg5 or ffmpeg6 might be eating a lot of your CPU / GPU depending on your hardware

**Comment by AlexPresso** [comment]
I have no idea if it would even work, you can start by trying `ffmpeg5` then try `ffmpeg6` if it's not working

**Comment by KidWar75** [comment]
Nop, doesn't work either with ffmpeg 5 or 6 :(

**Comment by AlexPresso** [comment]
Arf, sorry then, unfortunately, I can't do anything if the format is not supported by ffmpeg :(
