### ISSUE TITLE
[QA] Could the process of installing/uninstalling this patcher break Synology Application Service?

### ISSUE THREAD

**Issue by ner00** [AlexPresso/VideoStation-FFMPEG-Patcher#126]
This is probably a random one and completely out of context, but... after updating VideoStation last night I had to repatch since HEVC playback stopped working again. For some reason, after applying the patch it still wouldn't work, so I ended up uninstalling the patch, uninstalling FFmpeg, uninstalling VideoStation and restarting to try again. After restarting, **Synology Application Service** fails to start and a bunch of packages dependent on it also won't work. 

The package has a repair option, but all it does is give an error after a few seconds. I tried looking in the log center and weirdly it is empty, says "Unable to display logs due to insufficient free space" - which can't be right because the volume is fine and has at least 2TB of free space.

This is the type of thing that should be dealt with Synology support, unfortunately for me this is a DSM running on a PC so no official support for me. It's like some database got corrupted or something, Ive seen references to PostgreSQL around but nothing specific. I've been struggling for hours trying to fix this and don't seem to be closer, even went as far as reinstalling DSM over itself but the end result was the same, **Synology Application Service** is broken, cannot be repaired and any app that depends on it won't work.

Obviously this issue is out of scope of the wrapper, but I was hoping you could advise on which logs to look, if any to potentially find a way to resolve this? This is kind of a last ditch effort, I don't know what else to do. Thanks.

DSM 7.2-64570 Update 3 for context.

**Comment by ner00** [comment]
To be clear, DSM is working as far as I can see, although the logs in the Log Center being broken does worry me too. Apart from **Synology Application Service** and all apps depending on it, the system seems fine.

**Comment by AlexPresso** [comment]
Hi ner0,
We can check it together on Discord if you want, it will be easier (my username is alexpresso) but as a first guess, I would say it's not because of the patch, it's really only impacting CodecPack, VideoStation and ffmpeg

**Comment by ner00** [comment]
Weirdly resolved itself after hours of throwing everything and the kitchen sink at it... it failed to repair or reinstall for 6 hours or so and then when I was about to take a screenshot of the error the install process just worked after having failed the previous 20 times... (shrugs)
