### ISSUE TITLE
[QA] DS923+ and Transcoding Videos

### ISSUE THREAD

**Issue by KidWar75** [AlexPresso/VideoStation-FFMPEG-Patcher#136]
Please check the [FAQ](https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/wiki/FAQ) before posting any question.

**Question**
Hello,

Sorry if it's a noob question but I can't find any answers ^^
I have an issue with my DS920+ ; It might be replaced with by Synology with the DS923+
The DS923+ doesn't have a iGPU anymore (compared to the DS920+) which is used to Transcode video & audio.

I was wondering if it might be an issue with your patcher & DS Video / VideoStation if I end up with the DS923+.

I have loads of person using VideoStation on there iPhone / Android / Android Boxes / Apple TVs etc. I wouldn't want it to be an issue.. ^^

Thx for the help ! :)

Kid.

**Comment by AlexPresso** [comment]
Hello @KidWar75,

No worries, I'm happy to help if I can :)

As you said, the DS923+ doesn't have an iGPU. While it won't cause any issue with the patcher itself (you can patch any NAS of any architecture even if not having a GPU), you may be unable to play/transcode hardware encoded video formats like H.264 and H.265 (these formats are widely used).

I have no idea if that's a possible choice for you, but I would highly recommend choosing a NAS having an iGPU, specially if you're having a lot of users, a CPU without hardware transcoding will suffer a lot to play your movies even if you pre-transcode them with offline transcoding

Alex
