### ISSUE TITLE
[BUG] HEVC + [DTS or EAC3 or TrueHD] not being transcoded once patched (GStreamer)

### ISSUE THREAD

**Issue by EngMarc** [AlexPresso/VideoStation-FFMPEG-Patcher#18]
Refer to the prior list branched to this question
https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/issues/15#issuecomment-974916202

I have been patching VideoStation with Vincent compiled ffmpeg 4.x and videos have been playing fine in eac3, dts, truehd. Now, suddenly, they don't play anymore with most recent DSM update. I'm unsure why but did find a few wrinkles where there's additional ffmpeg binaries. Even after linking them to the ffmpeg 4.x community forum binary, eac3 videos still will not play. 

Alex suggested running the patcher.sh file. Looking through it, it seems identical to the steps I did except the patcher.sh puts a script inplace of the ffmpeg in /var/packages/VideoStation/target/bin directory which then goes through some logic to call the correct binary. This practice was used in the past prior to Vincent doing a native compile for the ffmpeg binary with supports all the options synology uses. Thus, the script was no longer needed. 

It appears that somewhere in the libraries (not modified by the script) there are still some prohibited codecs (e.g. eac3, dts, truehd). The real question is where are these codecs listed?

Here's the mods for ffmpeg4:

sudo -i
#
# these are a soft link to the ffmpeg binary that can be used instead.
#
mv /var/packages/VideoStation/target/bin/ffmpeg /var/packages/VideoStation/target/bin/ffmpeg.old
ln -sf /var/packages/ffmpeg/target/bin/ffmpeg /var/packages/VideoStation/target/bin/ffmpeg
mv /var/packages/CodecPack/target/bin/ffmpeg41 /var/packages/CodecPack/target/bin/ffmpeg41.old
ln -sf /var/packages/ffmpeg/target/bin/ffmpeg /var/packages/CodecPack/target/bin/ffmpeg41
mv /var/packages/VideoStation/target/bin/ffprobe /var/packages/VideoStation/target/bin/ffprobe.old
ln -sf /var/packages/ffmpeg/target/bin/ffprobe /var/packages/VideoStation/target/bin/ffprobe
mv /var/packages/VideoStation/target/bin/vainfo /var/packages/VideoStation/target/bin/vainfo.old
ln -sf /var/packages/ffmpeg/target/bin/vainfo /var/packages/VideoStation/target/bin/vainfo
cp -p /var/packages/VideoStation/target/lib/libsynovte.so /var/packages/VideoStation/target/lib/libsynovte.so.old
sed -i 's/eac3/BLAH/' /var/packages/VideoStation/target/lib/libsynovte.so
sed -i 's/dts/ZAP/' /var/packages/VideoStation/target/lib/libsynovte.so
sed -i 's/truehd/IGNORE/' /var/packages/VideoStation/target/lib/libsynovte.so

**Comment by AlexPresso** [comment]
@EngMarc

> Just checked and my libraries are not the same as referenced in your patcher.sh script. Here's mine:
libavcodec.so.58
libavdevice.so.58
libavfilter.so.7
libavformat.so.58
libavutil.so.56
libpostproc.so.55
libswresample.so.3
libswscale.so.5

Yes, these files aren't the same because this procedure is made for an older version of VideoStation on which it was better to replace the files on an ARMv8 architecture. Nowadays everyone is prompted to use the `--force-wrapper` argument while running the patcher (which injects the ffmpeg_wrapper instead).

> So, are you saying now that the ONLY work around is to use the ffmpeg-wrapper.sh script to redirect the ffmpeg call? Seems the compiled ffmpeg4.1 should support all the command line options that synology used (according to Vincent).

There's a reason for using the wrapper: It first tries to use the embeded ffmpeg (the one from synology) then tries to use the SynoCommunity's ffmpeg if it fails.
I need to retry it but not long ago, my video files weren't working by directly using the SynoCommunity's ffmpeg without the wrapper. I supposed if to be related to command args and/or the way it's working with Advanced Media Extensions

**Comment by EngMarc** [comment]
ok let me know what you find. Supposedly, Vincent compiled in all the command line args that synology was using but they may have added something that's missing. If so, we can let Vincent know to see if it can be added.

**Comment by EngMarc** [comment]
maybe dump a log out with the command line args for both calls?

**Comment by EngMarc** [comment]
Just a note, I did go into 
/var/packages/CodecPack/target/lib/ffmpeg41
and did the 
sed -i 's/eac3/BLAH/' libavcodec.so.58
This did change the behavior of the spinning red circle. It no longer spun and quick went to 'Audio format is not supported'. 

So, there are multiple places where they (synology) have stored the forbidden audio codecs. 
Do you know a quick way to search binaries for a string like 'eac3' and 'dts' and 'truehd'? I probably can figure it out but don't do UNIX so much anymore. 

I'm thinking that if we find all of them it should play with the community ffmpeg.

**Comment by EngMarc** [comment]
I also checked and my libraries are not the same as referenced in your patcher.sh script. Here's mine:
libavcodec.so.58
libavdevice.so.58
libavfilter.so.7
libavformat.so.58
libavutil.so.56
libpostproc.so.55
libswresample.so.3
libswscale.so.5

I did ln the ffmpeg41 in the CodecPack dir which didn't make any difference.

As for my CodecPack, there's only this in the bin dir:
ffmpeg33-for-surveillance
4 lrwxrwxrwx 1 root root 38 Nov 21 17:12 ffmpeg41 -> /var/packages/ffmpeg/target/bin/ffmpeg
ffmpeg41-for-synoface
ffmpeg41.old
synocodectool
vainfo

I tried also linking 'ffmpeg41-for-synoface' to ffmpeg4.1 and I did get an error that the audio code wasn't supported. 

That tells me that all the scripts are missing someplace new where the codecs that are ok to play are listed. 

I did find the synocodectool (/usr/syno/bin/synocodectool) which seems to add/delete or list codecs that are allowed. The question is what is this command looking at?

**Comment by AlexPresso** [comment]
The best way to look into bin files is to use disassemblers / decompilers (reverse engineering tools), I'm currently reversing `ffmpeg27` (it's the one I have on a DS218Play) on Ghidra:
![screen](https://i.ibb.co/TgbYvrv/Sans-titre.png)

**Comment by EngMarc** [comment]
What's that app? 
I've been out of coding a long time so not up on new tools, etc.
I'm on a MB Pro these days (which is unix underneath so I get to use my unix skills).

**Comment by AlexPresso** [comment]
https://ghidra-sre.org/

**Comment by EngMarc** [comment]
Thanks, do you know much about the synocodectool ?
It seems to be a codec management tool. I suspicious that this is somehow setting up multiple areas where codecs are authorized to play/view. This is newer and probably why our patching algorithms aren't catching all the spots that limit the codec (eac3, dts, truehd).  It updates/reads a file in /usr/syno/etc/cocec/activation.conf which has a list of the authorized codecs.

**Comment by AlexPresso** [comment]
No, I wasn't aware of that tool, have you tried to use the `--activate_codec` so far ?

**Comment by EngMarc** [comment]
yep, it just runs without any output. Did it as root.

**Comment by EngMarc** [comment]
Also read that all the ffmpeg binaries need to be linked. But wondering if there's some library codec check that is happening as when I linked the other binaries in the /var/packages/CodecPack/target/bin directory, I did get an error on the audio codec instead of the spinning red circle. So that means that there's some library or file someplace forbidding the code. We did find that in the one patched library libsynovte.so. I'm guessing there are more now.

**Comment by EngMarc** [comment]
This is where I found out about the synocodectool
https://github.com/dmc31a42/synocodectool-patch/blob/master/patch.sh

**Comment by AlexPresso** [comment]
From what I see in the code of `synocodectool`, it's very limited, you can only choose between those packages:
```cpp
  local_8 = __stack_chk_guard;
  if (param_1 != (char *)0x0) {
    memset(auStack4104,0,0x1000);
    iVar1 = strcmp(param_1,"videostation");
    if (iVar1 == 0) {
      pcVar2 = "Video Station";
    }
    else {
      iVar1 = strcmp(param_1,"audiostation");
      if (iVar1 == 0) {
        pcVar2 = "Audio Station";
      }
      else {
        iVar1 = strcmp(param_1,"mediaserver");
        if (iVar1 == 0) {
          pcVar2 = "Media Server";
        }
        else {
          iVar1 = strcmp(param_1,"surveillance");
          if (iVar1 == 0) {
            pcVar2 = "Surveillance Station";
          }
          else {
            pcVar2 = "DSM";
          }
        }
      }
    }
```

And only between those codecs:
```cpp
LAB_004033ec:
    __syslog_chk(3,1,"%s:%d bad parameter","SYNOCodecPatentG1.cpp",uVar4);
  }
  else {
    if ((param_2 == 0) || (iVar2 = FUN_00404160(&PTR_s_videostation_00419310,param_2), iVar2 != 0))
    {
      uVar4 = 0x59;
      goto LAB_004033ec;
    }
    iVar2 = strcasecmp(param_1,"aac_dec");
    if ((iVar2 == 0) || (iVar2 = strcasecmp(param_1,"aac_enc"), iVar2 == 0)) {
      std::__cxx11::basic_string<char,std::char_traits<char>,std::allocator<char>>::assign
                ((char *)&local_1f0);
    }
    else {
      iVar2 = strcasecmp(param_1,"h264_dec");
      if ((iVar2 == 0) || (iVar2 = strcasecmp(param_1,"h264_enc"), iVar2 == 0)) {
        std::__cxx11::basic_string<char,std::char_traits<char>,std::allocator<char>>::assign
                  ((char *)&local_1f0);
      }
      else {
        iVar2 = strcasecmp(param_1,"vc1_dec");
        if ((iVar2 == 0) || (iVar2 = strcasecmp(param_1,"vc1_enc"), iVar2 == 0)) {
          std::__cxx11::basic_string<char,std::char_traits<char>,std::allocator<char>>::assign
                    ((char *)&local_1f0);
        }
        else {
          iVar2 = strcasecmp(param_1,"mpeg4part2_dec");
          if ((((iVar2 == 0) || (iVar2 = strcasecmp(param_1,"mpeg4part2_enc"), iVar2 == 0)) ||
              (iVar2 = strcasecmp(param_1,"hevc_dec"), iVar2 == 0)) ||
             ((iVar2 = strcasecmp(param_1,"hevc_enc"), iVar2 == 0 ||
              (iVar2 = strcasecmp(param_1,"ac3_dec"), iVar2 == 0)))) {
            std::__cxx11::basic_string<char,std::char_traits<char>,std::allocator<char>>::assign
                      ((char *)&local_1f0);
          }
        }
      }
    }
  }
```

**Comment by EngMarc** [comment]
Ok, so then what I’m wondering does it do with the codec once authorized?
That’s where we’ll need to look for imbedded codecs that can be translated.

**Comment by AlexPresso** [comment]
`synocodectool` only read/writes JSON to the `activation.json` file, it's not accessing any other directory. Except making an httprequest to `https://codecstatistic.synology.com/codec_feedback.php` (probably for Synology analytics)

**Comment by EngMarc** [comment]
Ok that’s interesting. 
do you need the newer libraries from dsm 7.0.1?
I’m thinking of going through the stuff systematically to scour out hiccups causing the non playing of codecs even though the new ffmpeg4.1 will play them.

**Comment by AlexPresso** [comment]
If you mean that part:
>libavcodec.so.58
libavdevice.so.58
libavfilter.so.7
libavformat.so.58
libavutil.so.56
libpostproc.so.55
libswresample.so.3
libswscale.so.5

No it's okay, thanks, I'm on latest DSM 7 version too, the files used by the patcher are made for older VideoStation versions on ARMv8 (so they can still use it if not updating to latest version)

https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/issues/18#issuecomment-974922381

**Comment by AlexPresso** [comment]
I'll reverse VideoStation to check how it is dealing with Advanced Media Extensions, it will help us understanding which files are getting called / checked

**Comment by EngMarc** [comment]
Ok that will help a lot. You going to look at the newest videostation?

**Comment by AlexPresso** [comment]
yep

**Comment by AlexPresso** [comment]
There's an interesting env var right here (`SYNO_CODEC_SKIP_ACTIVATION`), don't know yet what we can do about it:
```cpp
  setenv("SYNO_CODEC_SKIP_ACTIVATION","yes",1);
  synovs::preprocess::VideoProber::VideoProber
            (aVStack120,pbVar2,(bool)pbVar2[0x41],(bool)pbVar2[0x40]);
  synovs::preprocess::VideoProber::Probe();
  unsetenv("SYNO_CODEC_SKIP_ACTIVATION");
  LibSynoVTE::preprocess::proto::PreprocessResult::PreprocessResult(this,aPStack104);
  synovs::preprocess::VideoProber::~VideoProber(aVStack120);
```

**Comment by EngMarc** [comment]
Interesting

**Comment by EngMarc** [comment]
How do you get the binary files off of the Synology? FTP?

**Comment by AlexPresso** [comment]
I copy them to a directory I can access from network

**Comment by EngMarc** [comment]
ahh, where are the synology file server folders when you're in a terminal on synology?

**Comment by AlexPresso** [comment]
near `/var/services/homes`

**Comment by EngMarc** [comment]
worked like a champ as I have drive station running so put it in my home dir. 
I copied down VideoStation, CodecPack, SurveillanceStation, MediaServer

Now the fun starts - not.

**Comment by EngMarc** [comment]
I copied them to the homes dir but where I’m located the network is so slow (600 kb/s) that I can’t look at them till late tomorrow. I copied videostation, code pack and mediaserver

**Comment by EngMarc** [comment]
Any other updates?

**Comment by AlexPresso** [comment]
Not for now, honestly, reversing these apps is a huge task and I don't have a lot of time to spend on it so... since then, the wrapper  workaround works, it's just not handling H.265 files correctly, but for others, everything is fine.

**Comment by AlexPresso** [comment]
Hey there,

I renamed the issue because the problem you're having is not related at all with my patcher but with the VideoStation behavior itself.

Today I analyzed a bit of the behavior of Advanced Media Extensions and VideoStation.

I can now tell that in the end you'll need the ffmpeg_wrapper in any case, I've also checked the CLI arguments used to run ffmpeg from VideoStation, there isn't enough informations provided to make ffmpeg able to "transcode" to another codec, because there's no other codec provided. This is only achieved by the wrapper.
Also, most of the browsers cannot decode H.265 at all, that's why it won't without having the wrapper transcoding it to another codec (https://caniuse.com/hevc).

**Comment by EngMarc** [comment]
Alex, I can play H.265 files with Videostation but it won't play any file with eac3 audio track. I've confirmed this many times. So, it isn't H.265 but the eac3 audio track that throws the error. This was well documented in the past the eac3, DTS and TRUEHD audio tracks.

**Comment by AlexPresso** [comment]
Yes, you are right, because you're not using the wrapper, transcoding from H.265 to another codec is done by Advanced Media Extensions, but this is also what is preventing you from reading eac3, dts and truehd.

There's is something kind of custom in the VideoStation's ffmpeg, making it call Advanced Media Extensions (haven't found it yet), that is why I think you can't work without the wrapper (having a pipe using both VideoStation's ffmpeg and SynoCommunity's ffmpeg) but when using that technique, H.265 doesn't work anymore.

**Comment by EngMarc** [comment]
So here's my fix :D
ffmpeg -i "input-eac3.mkv" -c:v copy -c:a ac3 -q:a 2 "input-ac3.mkv"

**Comment by AlexPresso** [comment]
Yes, pre-converting audio is also a good workaround if you want to keep HEVC ;)

I'll continue my investigations on the VideoStation's source code, I'm really near to understand the way it is "deciding" if it needs to use CodecPack or not:
![Sans_titre](https://user-images.githubusercontent.com/15526962/143856786-1039b49f-1841-44ee-9679-dd380f63a8d7.png)

**Comment by AlexPresso** [comment]
I'm getting closer:
![Sans titre](https://user-images.githubusercontent.com/15526962/143909322-8face5bb-b6da-4ac1-ad10-128af36c96be.png)

Now I need to try to edit it without breaking the library

**Comment by AlexPresso** [comment]
I'm closing this issue as it is related to #16 and #15

**Comment by EngMarc** [comment]
Alex,
How's things? I gave up on this and just downloaded the videos to play locally with VLC. 
When I got the above, I thought I'd check out what's been going on with this thread. 
I did try your 'patcher.sh' script but it didn't change the spinning red circle that never resolves. 

Not sure if you ever figured out the CodecPack thing or not.

![Screen Shot 2022-02-05 at 11 07 26](https://user-images.githubusercontent.com/48916817/152649258-b188dff5-078d-4058-8ccb-5892ac2adf63.png)

**Comment by AlexPresso** [comment]
Hi Marc,

I did a lot of reseach on that and I'm currently talking with the ffmpeg devs as it seems there's a bug with the video codec guessing somewhere.

There's no fix for it at the moment, that's why I'm closing this issue, my investigations are done for now, and I will continue to report any advancement in the issues I've attached above :).

**Comment by EngMarc** [comment]
ok thanks for all the investigative work. Keep me posted on anything you find out.
Marc
