### ISSUE TITLE
这是我找到的最棒的解决方案了！

### ISSUE THREAD

**Issue by npgwgmggta** [AlexPresso/VideoStation-FFMPEG-Patcher#24]
牛哇牛哇，这个方法解决了Video Stations、synology photos的视频略缩图的问题。找了好久，只有这个方案是目前完美解决的。
之前在百度找的方法最多最好的就是能解决大部分视频的略缩图问题，但是苹果的拍摄视频的高效格式HEIF/HEVC的视频还是不会显示略色图。这个方案就解决了。别人提的问题目前我是没有遇到过。
谢谢作者。

**Comment by AlexPresso** [comment]
Good evening,
Could you please post it in english ? Thank you

**Comment by refined-fish** [comment]
> Good evening, Could you please post it in english ? Thank you

Hello author, this friend did not give any bug feedback, he just expressed his thanks and praise to you. And me 2.

**Comment by AlexPresso** [comment]
Hello there,
Ooooh okay, I'm glad it helped you then :)
Thanks for replying
