### ISSUE TITLE
dsm 7.1 codec not working

### ISSUE THREAD

**Issue by PoepieFloepie** [AlexPresso/VideoStation-FFMPEG-Patcher#26]
**System details**
- Synology model: 220+
- DSM version: 7.1-42661 
- on DSM 7.0 it is working fine
- SynoCommunity FFMPEG Version: latest
- VideoStation version: latest
- Advanced Media Extensions version: latest

**Describe the bug**
video with dts eac3 and truehd the circle keeps spinning

**Comment by volkzp** [comment]
The same bug after updating to DSM 7.1-42661  

Synology model: DS920+
FFMPEG Version: latest
VideoStation version: latest
Advanced Media Extensions version: latest

**Comment by AlexPresso** [comment]
Is the video codec H.265 (HEVC) ?

**Comment by zetanary** [comment]
Same here, circle keeps spinning. 
Not work for any video (H264/H265) with audio  EAC3, DTS, TrueHD after upgrade to DSM7.1-42661.

Synology model: DS920+
SynoCommunity FFMPEG version: 4.3.3-39
VideoStation version: 3.0.3-2084
Advanced Media Extensions version: latest

**Comment by Fabian1601** [comment]
Same for me.

Synology model: DS1520+
SynoCommunity FFMPEG version: 4.3.3-39
VideoStation version: 3.0.3-2084
Advanced Media Extensions version: latest

**Comment by AlexPresso** [comment]
Strange, I need to investigate

**Comment by volkzp** [comment]
> Is the video codec H.265 (HEVC) ?

If you are asking about Advanced Media Extensions, then yes. ADE with HEVC codec support

**Comment by AlexPresso** [comment]
Yes, I'm asking specifically for this video codec, because it's a known problem I'm working on for a long time (see: #16 )

**Comment by Fabian1601** [comment]
I have the problems also with movies that worked fine under 7.0 with your patch

**Comment by zhonghaoyun240** [comment]
so？time？

**Comment by AlexPresso** [comment]
> so？time？

What ? Really ? You're asking it like I owe you any kind of service. I'm not. 
Be kind, let me find some time to fix it, or fix it yourself.

**Comment by findstevehere** [comment]
> so？time？

seriously dude?

**Comment by findstevehere** [comment]
always getting: 
Missing SynoCommunity ffmpeg package, please install it and re-run the patcher.

**Comment by Fabian1601** [comment]
strange, I get no message that something is missing.
the patch runs cleanly through

**Comment by AlexPresso** [comment]
> always getting:
Missing SynoCommunity ffmpeg package, please install it and re-run the patcher.

That is strange, have you successfully installed the package using the package manager ?

---
DSM 7.1 is not yet available for my DS218Play, I'll wait until monday to see if there's an auto update, and start investigating. If I still have no update until monday, I'll manually update it anyway.

**Comment by mblanco4x4** [comment]
Same here, manually updated to DSM 7.1 then repatched. Videos without dts seem to work but WITH dts it just spins and never begins playback. Was working great before. I will experiment some more.

Thanks!

Synology model: DS918+
SynoCommunity FFMPEG version: 4.3.3-39
VideoStation version: 3.0.3-2084
Advanced Media Extensions version: 2.0.0-1017

**Comment by findstevehere** [comment]
What is the procedure then if I'm missing something? I try to both with
audio station stopped or running. And with fmmpg pack installed

**Comment by mblanco4x4** [comment]
> 

Further testing, playback hangs with eac3 & dts audio files. DSM 7.1 patched.

Thanks!

**Comment by findstevehere** [comment]
I had it patched before the update successfully but have not been able to
do so again. But if it's not working anyways I guess there's no point
right?

**Comment by AlexPresso** [comment]
For now yes, I'll fix it, then we'll have a look on why it tells you don't have SynoCommunity ffmpeg :)

**Comment by zuendi123** [comment]
> Further testing, playback hangs with eac3 & dts audio streams. DSM 7.1 patched.
> 
> Thanks!

I have the same issue here. Syno was patched before on DSM 7.0.1. After update to DSM 7.1 and re-run the patcher, the playback with eac3 and dts audio streams hangs.

**Comment by kingjia1989** [comment]
> For now yes, I'll fix it, then we'll have a look on why it tells you don't have SynoCommunity ffmpeg :)

DSM7.1-42661 with ffmpeg 4.3.3-39, Video Station 3.0.3-2084.

I cannot find the direction: /var/packages/CodecPack. Could be the reason?

**Comment by OnePunchMan007** [comment]
First thanks for this amazing patcher ! 
I just want to say it doesn't work for me also in 7.1

**Comment by findstevehere** [comment]
> For now yes, I'll fix it, then we'll have a look on why it tells you don't have SynoCommunity ffmpeg :)

thanks buddy!

**Comment by ja-vivanco** [comment]
> > so？time？
> 
> What ? Really ? You're asking it like I owe you any kind of service. I don't. Be kind, let me find some time to fix it, or fix it yourself.

Alex, after reading that weird comment from [zhonghaoyun240] I just wanted to let you know how much the community apreciates all the effort you are putting into this in your free time, and how gratful we are because thanks to people like you with the knwoledge and willingness to share with others without expecnig anything in return, we can fully enjoy the feaures of the fantastic DSM software.

Thanks a lot Alex, and keep doing this at your own pace, whenever you have time avaiable and feel like it. And if at some point in time you decide that you can't or don't want to mantaining your patch any more, we'll totally understand and still be grateful for what you have been sharing with us all this time.

**Comment by OnePunchMan007** [comment]
@ja-vivanco  : 

here the step that work for me : 

- Run the patch from alex 
- cd /var/packages/CodecPack/target/bin
- sudo mv /var/packages/CodecPack/target/bin/ffmpeg41 /var/packages/CodecPack/target/bin/ffmpeg41.orig
- wget -O - https://raw.githubusercontent.com/darknebular/Wrapper_VideoStation/main/ffmpeg41-wrapper > /var/packages/CodecPack/target/bin/ffmpeg41
- sudo chmod 755 /var/packages/CodecPack/target/bin/ffmpeg41
- sudo sed -i -e 's/eac3/3cae/' -e 's/dts/std/' -e 's/truehd/dheurt/' /var/packages/VideoStation/target/lib/libsynovte.so
- sudo synopkg restart VideoStation

thanks to kidWar75 in the other forum
I just follow the step here :  https://github.com/darknebular/Wrapper_VideoStation

**Comment by cnstudio** [comment]
@OnePunchMan007 :

Your fix steps also work for me on DSM 7.1-42661 (All packages version are the latest).
Feedback this information for everyone who use DSM 7.1.

**Comment by jinlife** [comment]
It seems the codepack path changed from /var/packages/CodecPack/target/bin to /var/packages/CodecPack/target/**pack**/bin in 7.1.

**Comment by findstevehere** [comment]
> @ja-vivanco :
> 
> here the step that work for me :
> 
> * Run the patch from alex
> * cd /var/packages/CodecPack/target/bin
> * sudo mv /var/packages/CodecPack/target/bin/ffmpeg41 /var/packages/CodecPack/target/bin/ffmpeg41.orig
> * wget -O - https://raw.githubusercontent.com/darknebular/Wrapper_VideoStation/main/ffmpeg41-wrapper > /var/packages/CodecPack/target/bin/ffmpeg41
> * sudo chmod 755 /var/packages/CodecPack/target/bin/ffmpeg41
> * sudo sed -i -e 's/eac3/3cae/' -e 's/dts/std/' -e 's/truehd/dheurt/' /var/packages/VideoStation/target/lib/libsynovte.so
> * sudo synopkg restart VideoStation
> 
> thanks to kidWar75 in the other forum I just follow the step here : https://github.com/darknebular/Wrapper_VideoStation

oh thank you so much, really appreciate step by step... happy to collate or put these all together for others if I can get to work for me.  Will post any issues or confusion if they pop up. cheers

**Comment by AlexPresso** [comment]
@OnePunchMan007 Thanks for the infos, I'll have a look at it and try to implement these steps in the patch

**Comment by enr00ted** [comment]
I can confirm this is working for me too. Hoping for Alex's version with the possibility of rollback.

**Comment by findstevehere** [comment]
> AlexPresso

not sure how many times I've reported this, but Alex script gets an error that I need to install ffmpeg.. which I have installed already.

**Comment by findstevehere** [comment]
> > always getting:
> > Missing SynoCommunity ffmpeg package, please install it and re-run the patcher.
> 
> That is strange, have you successfully installed the package using the package manager ?
> 
> DSM 7.1 is not yet available for my DS218Play, I'll wait until monday to see if there's an auto update, and start investigating. If I still have no update until monday, I'll manually update it anyway.

huh? You mean did I install ffmpeg through Package manager? yes. is there some other way. Anyways. there's so many different threads now with references to 3 different peoples patches that it's nuts. Or reference to original patch directions in comments from 2 years ago with VS 6. whatever instructions followed by 7xxx instructions. All over the map, so hardly helpful especially with repeatedly getting Alex error stating "install ffmpeg"

**Comment by findstevehere** [comment]
> > @ja-vivanco :
> > here the step that work for me :
> > 
> > * Run the patch from alex
> > * cd /var/packages/CodecPack/target/bin
> > * sudo mv /var/packages/CodecPack/target/bin/ffmpeg41 /var/packages/CodecPack/target/bin/ffmpeg41.orig
> > * wget -O - https://raw.githubusercontent.com/darknebular/Wrapper_VideoStation/main/ffmpeg41-wrapper > /var/packages/CodecPack/target/bin/ffmpeg41
> > * sudo chmod 755 /var/packages/CodecPack/target/bin/ffmpeg41
> > * sudo sed -i -e 's/eac3/3cae/' -e 's/dts/std/' -e 's/truehd/dheurt/' /var/packages/VideoStation/target/lib/libsynovte.so
> > * sudo synopkg restart VideoStation
> > 
> > thanks to kidWar75 in the other forum I just follow the step here : https://github.com/darknebular/Wrapper_VideoStation
> 
> oh thank you so much, really appreciate step by step... happy to collate or put these all together for others if I can get to work for me. Will post any issues or confusion if they pop up. cheers

sure good luck with that when Alex patch gets error: "install ffmpeg" and then next command results in "no such file or directory"  

It would be so nice if someone could provide termninal instructions for mac that work,. cheers

**Comment by OnePunchMan007** [comment]
@findstevehere i think you should create another issues because it's seems diffrent. Have you try ot upatch everything then uninstall evertyhing and then resinstall (Adanced Media Extensions , Video Station and ffmpeg from th0ma7)

**Comment by Swiftfrog** [comment]
> https://github.com/darknebular/Wrapper_VideoStation

Hi Bro, that's very useful for DSM7.1, thanks so much!!!

**Comment by AlexPresso** [comment]
The patch from DarkNebular doesn't work when medias are both encoded with HEVC and DTS or EAC3

**Comment by findstevehere** [comment]
> The patch from DarkNebular doesn't work when medias are both encoded with HEVC and DTS or EAC3

I thought you asked for info somewhere but don't see it now....but this is what I get when I use the basic patch


MacBook-Air:~ root# curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/main/patcher.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3660  100  3660    0     0   4146      0 --:--:-- --:--:-- --:--:--  4211
cat: /etc.defaults/VERSION: No such file or directory
[2022-05-03 20:45:09] [INFO] ffmpeg-patcher v1.5
[2022-05-03 20:45:10] [Message of the day] 

The patcher was redesigned to include an unpatch procedure.

I'm aware of an issue with HEVC and I'm working on it.

As always, please let me know of any issue you could have.

[2022-05-03 20:45:10] [ERROR] Missing SynoCommunity ffmpeg package, please install it and re-run the patcher.
MacBook-Air:~ root#

**Comment by findstevehere** [comment]
but I also install ffmpeg from package centre but not through a manual install, just select from community

**Comment by AlexPresso** [comment]
Thé problem is that you're trying to install the patch on your Mac. You need to connect to the NAS through QSH before you run these commands (follow the help link on the repo)

**Comment by findstevehere** [comment]
> * sudo mv /var/packages/CodecPack/target/bin/ffmpeg41 /var/packages/CodecPack/target/bin/ffmpeg41.orig

i just get error there is no file or directory. seems ffmpeg doesnt exist in my root folder or whatever

**Comment by realaaa** [comment]
if anyone has this error 

`[ERROR] Missing ffmpeg package, please install it and re-run the patcher.`

I just got it on 7.2.2 and VideoStation-FFMPEG-Patcher-3.2

it checks for /var/packages/ffmpeg directory 

```
+ [[ ! -d /var/packages/ffmpeg ]]
+ error 'Missing ffmpeg package, please install it and re-run the patcher.'
+ log ERROR '\e[0;31m' 'Missing ffmpeg package, please install it and re-run the patcher.\n'
++ date '+%Y-%m-%d %H:%M:%S'
+ printf '\e[0;37m[%s] \e[0m[%s] %b' '2025-05-03 22:38:20' ERROR '\e[0;31mMissing ffmpeg package, please install it and re-run the patcher.\n'
[2025-05-03 22:38:20] [ERROR] Missing ffmpeg package, please install it and re-run the patcher.
+ missingDeps=1
+ [[ 1 -eq 1 ]]
+ exit 1
```

while I had ffmpeg6 and 7 - so just do a symlink - then it works 

```
# ln -s /var/packages/ffmpeg6/ /var/packages/ffmpeg

# ls -ld /var/packages/ffmpeg*
lrwxrwxrwx 1 root root   22 May  3 22:39 /var/packages/ffmpeg -> /var/packages/ffmpeg6/
drwxr-xr-x 5 root root 4096 May  3 21:03 /var/packages/ffmpeg6
drwxr-xr-x 5 root root 4096 May  3 21:08 /var/packages/ffmpeg7
```

**Comment by AlexPresso** [comment]
You can also use the `-v 6` option to make the patcher know that you want to use ffmpeg 6

The patcher will then check for the right package and make the correct symlink
