### ISSUE TITLE
[QA] Support Photos and Surveillance Station H265 video Thumbnail

### ISSUE THREAD

**Issue by dogodefi** [AlexPresso/VideoStation-FFMPEG-Patcher#35]
**Question**

First of all, thank you very much for your patch, after installing it, my Surveillance Station real-time video (H265 format) can get thumbnails normally. But still unable to get thumbnails of recorded videos of Synology Photos and Surveillance Station. Do you have any tips or solutions?

**Comment by AlexPresso** [comment]
Hi,
I'm glad you like the patch.
Do you mean VideoStation is unable to recover video thumbnails ? or the other apps ?

**Comment by dogodefi** [comment]
In my case,  VideoStation,Synology Photos,Surveillance Station all can not show video thumbnails

**Comment by AlexPresso** [comment]
Is it only happening on recorded/personal videos or also on downloaded movies / series ?

**Comment by dogodefi** [comment]
I did't test download video. but my gopro record viedo(HEVC format) can't show thumbnails.

**Comment by AlexPresso** [comment]
Unfortunately, I have no idea what it does this, the patch isn't editing that part
