### ISSUE TITLE
[QA] Extend the patch to the media server (DLNA)

### ISSUE THREAD

**Issue by chocobidou** [AlexPresso/VideoStation-FFMPEG-Patcher#37]
Before all, I really appreciate the script you made, it's usefull and really accurate.

I've applied the patch and everything works on VideoStation but do you know if it's possible to apply the same patch to the DLNA media server because same files don't work on my TV

Best regards

**Comment by AlexPresso** [comment]
Hi,

For now, I haven't checked DLNA at all, it's something I'm planning to do but I need to fix some things in Advanced Media Extensions before I have a look at it.
If you have a SmartTV, the best option you could have for now would be to install the VideoStation app on your SmartTV

**Comment by chocobidou** [comment]
Hello
Unfortunately, DS Video and VideoStation don't exist for my LG C9 Web OS and when I try to open the app with the embedded navigator, it fail during loggin. 

 If you want some help, I'm in !

**Comment by akvamassa** [comment]
Hello, it's me again)) I found this thread :) Will subscribe to it. Hope you will find out some solution. Thank you and good luck)

**Comment by AlexPresso** [comment]
Made another patcher for this one https://github.com/AlexPresso/MediaServer-ffmpeg-patcher :)
