### ISSUE TITLE
[BUG] dvvideo plays sound but black video

### ISSUE THREAD

**Issue by Subtixx** [AlexPresso/VideoStation-FFMPEG-Patcher#39]
**System details**
- Synology model: DS3617xs
- DSM version: 6.2
- SynoCommunity FFMPEG Version: 4.4.2-43
- VideoStation version: 2.4.10-1632
- Advanced Media Extensions version: none

**Describe the bug**
A video using dvvideo codex shows a black image but plays the sound.

```
Resolution: 720 x 576
Container: dv
Videocodec: dvvideo
Audiocodec: pcm_s16le
Videobitrate: 28141.7 Kbps
```

**FFMPEG logs**
https://gist.github.com/Subtixx/aedb7818be53f67054826f5df7018280

**Comment by AlexPresso** [comment]
Hm... interesting, could you provide me the following logs please:

## `ffmpeg-FFMxxxx.stderr` (containing chunks transcoding operations)
- Run the movie (let it play in background) and connect through SSH
- switch to root user `sudo -i`
- When you run `ls -al /tmp | grep ffmpeg` you should see another file that looks like `ffmpeg-FFMxxxx.stderr`
- Type `tail -100 ffmpeg-FFMxxxx.stderr` (replacing the filename by the correct one)
- Copy paste those lines in a new [gist](https://gist.github.com/)
- Type `head -300 ffmpeg-FFMxxxx.stderr` (replacing the filename by the correct one)
- Copy paste those lines in another new [gist](https://gist.github.com/)
- Copy paste all the gists links in a new comment :)

**Comment by Subtixx** [comment]
It wasn't possible for me to do tail-100 nor head -300 because the file is gone in 1-2 seconds. BUT I managed to grab it one time using WinSCP by reloading really fast.

https://gist.github.com/Subtixx/2fdae61bab6c66721b34a517a80356dd

**Comment by AlexPresso** [comment]
Really interesting, thanks for the investigations, I suppose it is related to the video codec, ffmpeg gives a warning about it:
`[swscaler @ 0x8fcb20] deprecated pixel format used, make sure you did set range correctly`

The wrapper may handle it badly. As I'm currently re-writing the wrapper in #33, if for now, you're okay with manually converting this video codec, I'll come back to you once it is merged so we can try again and see if it's fixed or not.

**Comment by Subtixx** [comment]
Ok thanks, would be great. A pain to have two copies of each video but oh well.

Also I noticed VideoStation / ffmpeg cannot handle interlaced video. Is that something you could look into aswell?

**Comment by AlexPresso** [comment]
ffmpeg does handle interlaced video but I think VideoStation doesn't.

It's something I can probably look into if I have time, after all bugs are fixed. But if VideoStation doesn't support it natively (I mean without using the wrapper), it would be like adding a new feature to VideoStation and it's not really what the wrapper is meant to be.

I'd like to keep it simple and only have it acting like a pass-through to the SynoCommunity's ffmpeg, which is compiled with everything needed to encode/decode audio codecs that are supported, but have been explicitly denied by Synology.

Adding this kind of features to VideoStation is not an easy task, the ffmpeg args are statically generated by a function in `libsynovte.so` and directly passed to the wrapper. I could catch some of these args or completely re-generate args by probing the video file but it requires a lot of time to spend on testing and debugging.

**Comment by AlexPresso** [comment]
Hi Subtixx, does the new wrapper fixes this issue ?
