### ISSUE TITLE
[BUG] no transcode time

### ISSUE THREAD

**Issue by Fabian1601** [AlexPresso/VideoStation-FFMPEG-Patcher#4]
**System details**
- Synology model: ds1019+
- DSM version: 7.0-41882
- VideoStation version: 3.0.1-2067
- Advanced Media Extensions version: 1.1.0-0201
- ffmpeg version: 4.3.2-37

**Describe the bug**
when converting a film, the time remains at -1: -1: -1
however, the film is successfully converted

**FFMPEG logs**
https://gist.github.com/Fabian1601/7557e0d316d6706609b88b59cc17e8e3#file-gistfile1-txt

**Comment by AlexPresso** [comment]
Hey,
Thanks for the report, I've pushed a fix.
To fix your current installation please:
- uninstall both Advanced Media Extensions and VideoStation (there's an option to keep your current movie database)
- re-install Advanced Media Extensions and VideoStation (you can start both of them)
- re-use the patcher

**Comment by AlexPresso** [comment]
The patcher has been updated to fix the Advanced Media Extensions patching, could you please try to:
- both uninstall VideoStation (keep library) and Advanced Media Extensions
- reinstall VideoStation (it should ask to install Advanced Media Extenstions, click yes)
- follow the patcher steps from the main branch

**Comment by Fabian1601** [comment]
I let your script run over it today.
you are a genius!
everything is going as it should. no error message, all films are played without a message and even the transcoding time works!

what you could perhaps add to the instructions is that you have to run the script again after an update of advanced media extension.
