### ISSUE TITLE
Low FPS after updating to last DSM

### ISSUE THREAD

**Issue by cptspartano** [AlexPresso/VideoStation-FFMPEG-Patcher#42]
**System details**
- Synology model: DS220+
- DSM version: 7.1-42661 Update 2
- SynoCommunity FFMPEG Version: 4.4.2-44
- VideoStation version: 3.0.3-2084
- Advanced Media Extensions version: 2.0.0-1017

**Describe the bug**
Hi! Great work with this patch. I still don't understand why Synology can make something like this official so we can watch videos without problems.

Anyway, everything worked greatly until yesterday that I updated DSM to the last version. Now when trying to play a video directly from Video Station (through the web) it sounds fine, but the video is laggy, playing at low fps, so it's uncomfortable to watch (for example has happened with the last episodes of both Obi-Wan and Ms. Marvel from today). Also some videos directly don't show image but play sound (e.g. previous episodes of Obi-Wan that worked fine previously to the update). I don't know if it is because of your patch that needs to adpat somehow to the newer versions of VideoStation and AME, or maybe it is because of FFMPEG. Anyway, I though you needed to know about this issue just in case :D

**Provide Log files**
- Start the video on VideoStation, wait for the video to play and put the browser in background (keep the video playing)
- Connect through SSH ([help](https://www.synology.com/en-global/knowledgebase/DSM/tutorial/General_Setup/How_to_login_to_DSM_with_root_permission_via_SSH_Telnet))
- Switch to root user: `sudo -i`

## `ffmpeg.log` (containing the ffmpeg-wrapper execution logs)
https://gist.github.com/cptspartano/1df0583c60ea5bba686e77ed81d368ab

## `ffmpeg-FFMxxxx.stderr` (containing chunks transcoding operations)
tail: https://gist.github.com/cptspartano/f3ec38c2a1bd836ad13c203e14a3c3eb
head: https://gist.github.com/cptspartano/d2c82c66c27b6b7040da8f2bbeb2fe53

If you need anything else let me know!

**Comment by AlexPresso** [comment]
Hi, thank you, I'm glad you like it :).
Synology could make it work, the main reason they don't implement it is because they don't want to, these codecs (DTS, EAC3 and TrueHD) are licensed, it means that Synology would have to pay a global licence fee based on every Synology users each year to make it possible, I don't think they will.

About your issue, I'm currently working on a new wrapper, could you please try the following:
- connect through SSH and switch to root user, like you did for the logs
- unpatch using the following command: `curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/main/patcher.sh | bash -s -- -a unpatch`
- repatch using the new wrapper: `curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/main/patcher.sh | bash -s -- -b new_wrapper`

**Comment by cptspartano** [comment]
Just tried it, and the videos with black image now has the normal image, but the low FPS problem still remains :_D

I know about the licenses problem, I read it when trying to find a solution. The thing is, I think they should find a solution or an alternative either way (I don't know, maybe making VideoStation an open source option could save them the money, like with VLC or Jellyfin?). For now, I can manage accessing locally the files through my computer or Chromecast, but when I'm out of my home I don't want to download the files on my own computer. I know there are alternatives as Emby, Plex or Jellyfin but they didn't work as good as Video Station: Plex couldn't make it work, Jellyfin was VERY slow (I'm guessing because it was running in a Docker instead of his own app) and a lot of thing weren't working as they should be, and Emby I think you have to pay for some features.

Anyway, your work is a lifesaver for making VS working properly (apart for the problem I'm having now)

**Comment by cptspartano** [comment]
Okay I found the problem. It was because of Chrome, not VideoStation or your patcher. I just went to watch a Youtube video and was happening the same. I've restarted the computer and now everything plays fine. Sorry to bother you in the end, and again thanks for your work!
