### ISSUE TITLE
[BUG] Script didn't start

### ISSUE THREAD

**Issue by NicolasVerachtert** [AlexPresso/VideoStation-FFMPEG-Patcher#47]
**System details**
- Synology model: DS918+
- DSM version: DSM 7.1-42661 Update 4
- SynoCommunity FFMPEG Version: 4.4.2-46
- VideoStation version: 3.0.4-2107
- Advanced Media Extensions version: 2.0.1-1021

**Describe the bug**
Running the latest version of the patcher didn't work.
I received no output in the terminal. (besides the curl overview)
Seems like the script didn't start. Also didn't find any logfiles

I downloaded the previous version of the patcher (curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/4535c6ae6759178150f9ee1696953c3196ed993/patcher.sh | bash): this worked immediately.

**Comment by AlexPresso** [comment]
Hey there,
Any console output while using the latest version?

**Comment by NicolasVerachtert** [comment]
Hi Alex,
Copy pasted from the terminal...
Does this help? 

curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/main/patcher.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4390  100  4390    0     0  17991      0 --:--:-- --:--:-- --:--:-- 17991

**Comment by AlexPresso** [comment]
Sorry, I pushed a regressing yesterday, here is the fix ;)
