### ISSUE TITLE
[BUG] Subtitles aren't working anymore on iPhone 13 Pro & iOS 16.0.2 via DS Video

### ISSUE THREAD

**Issue by KidWar75** [AlexPresso/VideoStation-FFMPEG-Patcher#49]
**System details**
- Synology model: **DS920+**
- DSM version: **DSM 7.1-42661 Update 4**
- SynoCommunity FFMPEG Version: **4.4.2-46**
- VideoStation version: **3.0.4-2107**
- Advanced Media Extensions version: **2.0.1-1021**

**Describe the bug**
The subtiltes doesn't appear anymore on my iPhone 13 Pro - iSo 16.0.2 (on any video) with DS Video
Whether de subtitles are embedded in the .mkv or with a .srt file.

Note : There is no problem of subtitles while using VideoStation on my PC.

## `ffmpeg.log` (containing the ffmpeg-wrapper execution logs)
- https://gist.github.com/KidWar75/331754e2f09f4f64d14aa3807c3a64ee

## `ffmpeg-FFMxxxx.stderr` (containing chunks transcoding operations)
- There is not ffmpeg-FFMxxxx.stderr :
![image](https://user-images.githubusercontent.com/62625228/194767979-34773ee2-338d-40a7-b091-803b045ba82f.png)

**Additional context**

**Comment by AlexPresso** [comment]
Hi KidWar, thanks for the issue :)

I would just need the content of `ffmpeg-17398.stderr` and `ffmpeg-19206.stderr` please

**Comment by KidWar75** [comment]
Hey @AlexPresso,

I've tried to redo the process for the logs and now I only got that : 
![image](https://user-images.githubusercontent.com/62625228/195300487-8ed0bb6b-616c-41bb-a060-b3bae7c661c7.png)

**Comment by KidWar75** [comment]
OK so here is what I got : 
ffmpeg.log : https://gist.github.com/KidWar75/0c2304354daa8e066a698d9bfecfe135 (my video playing is Atlanta.S04E05.Work.Ethic.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv)

Then I found only 1 file .stderr :
![image](https://user-images.githubusercontent.com/62625228/195304524-99067dfd-07e6-4aea-a86b-412f8e80b99e.png)
Here is the logs : https://gist.github.com/KidWar75/b1f983709e2afe82ddb4d1d8420ca282

Hope that helps... :)

**Comment by KidWar75** [comment]
@AlexPresso FYI, Out of curiosity, I tried the other's prick wrapper. And I don't have any subtitles either while using DS Video and my iPhone.
I guess it's a problem with the phone & my application (or maybe the new iOS...), I don't know...

**Comment by AlexPresso** [comment]
I'm glad to read it ahah. Yeah, it could be but I can check it easily with my android phone, I was able to reproduce the issue, I just don't have time to work on it for now unfortunately

**Comment by KidWar75** [comment]
Ye, take your time ;)

**Comment by KidWar75** [comment]
New info : I just upgrade my iPhone 13pro for a 14 pro. Even with the new iOS (16.0.3) ; Same issue with the subtitles on DS Video

**Comment by KidWar75** [comment]
Hoy ! Any news ?

**Comment by AlexPresso** [comment]
Hi,
Do you also have the issue when running unpatched VideoStation ?

**Comment by KidWar75** [comment]
Hey !
Just unpatched VS and still no subtitles (.srt or embedded) :(

**Comment by AlexPresso** [comment]
Yeah, I tried some stuff at home and it seems like it's a VideoStation bug

**Comment by ner00** [comment]
This probably doesn't help at all, but I've stopped using DS video app since day one. My preferred way to stream is opening the files in VLC using DS file app.

**Comment by KidWar75** [comment]
> This probably doesn't help at all, but I've stopped using DS video app since day one. My preferred way to stream is opening the files in VLC using DS file app.

I hear you, it's working fine with VLC using DS File app.
But I'm not the only one using my server and VS :')

**Comment by KidWar75** [comment]
> Yeah, I tried some stuff at home and it seems like it's a VideoStation bug

It's rather a DS Video bug rather than VideoStation, no ?
Cause the subs on VideoStation while streaming on my browser is working just fine.

**Comment by ner00** [comment]
DS video seems to use some flavour of MX Player (at least on Android). One of reason why I stopped using it was that subtitles were either misidentified or missing, partially or entirely. I assume this bug is entirely down to the video player used by DS video app.

**Comment by KidWar75** [comment]
> DS video seems to use some flavour of MX Player (at least on Android). One of reason why I stopped using it was that subtitles were either misidentified or missing, partially or entirely. I assume this bug is entirely down to the video player used by DS video app.

I never had any problems before, this is so weird

**Comment by AlexPresso** [comment]
I also have the issue with my Android phone so I suppose they broke something in the app :/

**Comment by KidWar75** [comment]
Hey Alex, any progress on your end ?
I'm using VLC via FileStation for the workaround.

**Comment by AlexPresso** [comment]
Hi,
Unfortunately I also have the issue on my android phone and despite my attempts, I wasn't able to make it work because I have no way from the wrapper, to identify if subtitles are enabled pn DS Video side or not.

DS Video is just not passing the args with subtitles to ffmpeg
