### ISSUE TITLE
[BUG] offline transcode runs through but gives an error at 100% and does not create the file

### ISSUE THREAD

**Issue by Fabian1601** [AlexPresso/VideoStation-FFMPEG-Patcher#50]
**System details**
- Synology model: ds1520+ with dx517
- DSM version: 7.1.1-42962 Update 1
- SynoCommunity FFMPEG Version: 4.4.2-46
- VideoStation version: 3.0.4-2107
- Advanced Media Extensions version: 3.0.1-2004

**Describe the bug**

offline transcoding runs without problems but no file is created at 100% but an error is issued that the network connection is unstable 

## `ffmpeg.log`

https://gist.github.com/Fabian1601/317246375e6ca5eb3a94f764b50c1713.js

## `ffmpeg-FFMxxxx.stderr`

https://gist.github.com/Fabian1601/c560d46b3ae98fdf68505f65b46d8936.js

**Comment by Fabian1601** [comment]
hello alex

i tried a little bit today, uninstalled vs etc and reinstalled step by step.
even with a movie (h264) that i can transcode successfully without script, it doesn't work after the script....
it always comes the error the system is busy or the network unstable.
do you have any ideas?

greetings fabian

**Comment by AlexPresso** [comment]
Hi Fabian, currently don't have much time to look at it, but I'll do when I can

**Comment by Fabian1601** [comment]
Hello alex,

Have you found some time to look at the problem?
At the moment I'm traveling a lot and have to convert the movies for ipad via handbrake in a roundabout way...

Greetings Fabian
