### ISSUE TITLE
[QA] Automatic repatch

### ISSUE THREAD

**Issue by Mavyre** [AlexPresso/VideoStation-FFMPEG-Patcher#51]
**Question / Enhancement**

Could it be possible to automatically repatch VideoStation? It might be at reboot time, or checking every hour if the repatch is needed, for instance. We, maybe, could use the task planner within DSM, but I doubt it has root access. 

Has anyone tried that, yet?

**Comment by AlexPresso** [comment]
Hey there, 
It's a wonderful idea.
I can check if I can access the Syno crontab, if so, I could add a cronjob while installing the patch, but it may not appear in the DSM UI

**Comment by JajajTec** [comment]
You alredy can!
Just add the command as a execution-job on system start in the task-manager.
If you dont know how, say it!

**Comment by AlexPresso** [comment]
Yeah, I know there are some Syno hardware on which you can do it.
But like on my DS218Play, you don't have this feature, the goal is to have it work on every architectures so I need to make sure I can do it using the native Linux crontab.

**Comment by AlexPresso** [comment]
Hey there,

Testers needed for the new patcher (with update action), if you want to test the new patcher :
- uninstall previous wrapper : `curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/main/patcher.sh | bash -s -- -a unpatch`
- install wrapper using the new patch : `curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/update_action/patcher.sh | bash -s -- -a patch -b update_action`

Testing the update scheduled task: [see this page](https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/blob/update_action/README.md#automated-updates) but until the changes are merged on the main branch, use the following script:
```shell
#!/bin/bash
curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/update_action/patcher.sh | bash -s -- -a update -b update_action
```

**Comment by Fabian1601** [comment]
Hello Alex, 
The script runs through with me without problems :) 
Maybe as a suggestion for improvement, if the script is up to date, theoretically no restart of the packages would be necessary or?

DS1520+ with DX517
DSM 7.2-64216 Beta
VS 3.1.0-3107 Beta
AMC 3.1.0-3004 Beta
ffmpeg 4.4.3-48

**Comment by AlexPresso** [comment]
Hi Fabian,
Thank you for testing :)
About the restart, I thought about it for a while and I prefer to restart the packages just in case I also change the patching procedure in a new version or the wrapper

**Comment by AlexPresso** [comment]
Hey there,
After a few tries and thinking about the problem, I think it's better to not add this feature, as any issue either on github, version check or in my code, can lead to unexpected results and brick VideoStation's installation.

The easiest and safest way if you want to achieve (very close to) automatic update is to create a scheduled task with root permission and something like the following script:

```
curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/main/patcher.sh | bash -s -- -a unpatch
curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/main/patcher.sh | bash -s -- -a patch
```
