### ISSUE TITLE
[QA] Please support proxy for the shell script.

### ISSUE THREAD

**Issue by AntaresQAQ** [AlexPresso/VideoStation-FFMPEG-Patcher#54]
People in some special areas have difficulty accessing github.com without a proxy. 
Could you please support proxy with an option like `...patcher.sh | bash -s -- -p http://127.0.0.1`?

**Comment by AlexPresso** [comment]
Sure, I'll add it

**Comment by AntaresQAQ** [comment]
> Sure, I'll add it

Thank you very much for your help!
