### ISSUE TITLE
Cannot play any HEVC file, even with supported codec

### ISSUE THREAD

**Issue by deprekate** [AlexPresso/VideoStation-FFMPEG-Patcher#56]
Everything is updated, done in proper order (multiple times)

**System details**
- Synology model: DS416j
- DSM version: DSM 7.1.1-42962 Update 3
- SynoCommunity FFMPEG Version: 4.4.3-47
- VideoStation version: 3.0.5-2503
- Advanced Media Extensions version: 3.0.1-2004

**Describe the bug**
I cannot get ANY hevc file to play with VideoStation, even with a supported codec [no DTS, no EAC3, no TrueHD].
I have been trying off and on to get hevc working on my DS416j, I am currently dealing with Synology support, since it might be a bug with my model.  Like the other who has a DS218, I do not have a gstreamer binary.  There is also no output or error messages on the Synology to help diagnose, all I get is a "The format of this video is not supported" from the VideoStation app on my Iphone or ipad, or when I use Chrome/Firefox/Safari browswer on Win10 or OSX

I have made a bunch of videos with different combinations of A/V codecs to help trouble shoot:
https://github.com/deprekate/VideoStation-FFMPEG-Patcher/tree/main/tests
I can request a pull if you would like to include these files in your repo (they are small and copyright free)
Like, the x265 with mp3 codec should play fine through VideoStation + ffmpeg + AME + Patcher right?

The only thing that the Patcher does it let me play x264 with eac codec, the table for what plays on my DS is:
|has| |mp3|aac|ac3|eac|dts|
|-|-|-|-|-|-|-|
|VS+ffmpeg+AME|x264|Y|Y|Y|N|N|
|VS+ffmpeg+AME|x265|N|N|N|N|N|
|VS+ffmpeg+AME+Wrapper|x264|Y|Y|Y|Y|N|
|VS+ffmpeg+AME+Wrapper|x265|N|N|N|N|N|

**Provide Log files**

## `ffmpeg.log` (containing the ffmpeg-wrapper execution logs)
https://gist.github.com/deprekate/ccadeff85a708cf461a4dd3a053991ae

## `ffmpeg-FFMxxxx.stderr` (containing chunks transcoding operations)
there is no .stderr file

**Additional context**
There is nothing interesting in /var/log/packages/ files:
CodecPack.log      ffmpeg.log    VideoStation.log

The only suspicious error messages I get are in the /var/log/apparmor.log file:
https://gist.github.com/deprekate/73c1b5b171669ec23b8e781e7cdb01b5
I don't know if these messages means apparmor blocked AME from getting/installing the proper hevbc codecs, or if Apparmor just blocked AME from checking for updates.

Both the green checkmarks are green in AME for HEVC and AAC

I am VERY proficient in linux and other stuff, but I am at a loss here.   Any ideas I could try to help figure out whats going on?

**Comment by AlexPresso** [comment]
Hi Deprekate,

Thanks for your these very accurate investigations and test cases.
You are right, this is a very strange behavior. 

> I have been trying off and on to get hevc working on my DS416j, I am currently dealing with Synology support, since it might be a bug with my model. Like the other who has a DS218

Yes, if HEVC is not working with supported codecs, on an unpatched VideoStation, there might be a bug on AME or VS side

About the `.stderr` files, I think you probably noticed it but just to be sure: they're only filled while the ffmpeg process is running, as soon as the parent process (VideoStation's player) is killed, the file is removed, did you also check for these files while the process is (supposed to be) running ? 

I would also need the following files to compare them please:
- `/var/packages/VideoStation/target/bin/ffmpeg`
- `/var/packages/VideoStation/target/bin/ffmpeg.orig`

And an output of `ls -al /var/packages/CodecPack/target/pack/bin` please.

> The only suspicious error messages I get are in the /var/log/apparmor.log file:

We will check about it later but I don't think they're related to the patch, are you using any "custom" VideoStation plugin to fetch videos metadata ?

**Comment by deprekate** [comment]
Well I went though a lot of Syno support, and I guess my model is not capable of playing HEVC videos.  I guess it also applies to all [Group 2](https://kb.synology.com/en-uk/DSM/tutorial/Can_my_Synology_NAS_convert_videos_for_my_device) models.  

So, I just ditched VideoStation and used an old laptop to make a Jellyfin server instead.
