### ISSUE TITLE
mkv内置字幕没识别出来

### ISSUE THREAD

**Issue by friendtasy** [AlexPresso/VideoStation-FFMPEG-Patcher#58]
# Before posting any bug issue, please make sure you have patched a clean VideoStation / AME install by doing the following:
- Uninstall VideoStation (keep your library)
- Uninstall Advanced Media Extensions
- Re-install VideoStation (it should also ask to install Advanced Media Extensions)
- Run the patch

**System details**
- Synology model: [Synology NAS model]
- DSM version: [version]
- SynoCommunity FFMPEG Version: [version]
- VideoStation version: [version]
- Advanced Media Extensions version: [version / "none" if you don't have it installed]

**Describe the bug**

**Provide Log files**
- Start the video on VideoStation, wait for the video to play and put the browser in background (keep the video playing)
- Connect through SSH ([help](https://www.synology.com/en-global/knowledgebase/DSM/tutorial/General_Setup/How_to_login_to_DSM_with_root_permission_via_SSH_Telnet))
- Switch to root user: `sudo -i`

## `ffmpeg.log` (containing the ffmpeg-wrapper execution logs)
- Go to the temporary directory: `cd /tmp`
- Type `ls -al | grep ffmpeg` to list all files containing "ffmpeg" and check you have one named `ffmpeg.log`
- Type `tail -200 ffmpeg.log` to print the last 200 lines to the console
- Copy paste those lines in a new [gist](https://gist.github.com/)
- Add the gist link to the issue

## `ffmpeg-FFMxxxx.stderr` (containing chunks transcoding operations)
- When you ran `ls -al | grep ffmpeg` you should have seen another file that looks like `ffmpeg-FFMxxxx.stderr`
- Type `tail -100 ffmpeg-FFMxxxx.stderr` (replacing the filename by the correct one)
- Copy paste those lines in a new [gist](https://gist.github.com/)
- Type `head -300 ffmpeg-FFMxxxx.stderr` (replacing the filename by the correct one)
- Copy paste those lines in another new [gist](https://gist.github.com/)
- Copy paste all the gists links in the issue

**Additional context**

dsm 6.2.4 videostation 2.5，试过很多方法都是转圈不出画，博主的东西倒是可以出画了，不过mkv内置字幕没识别出来，这个应该可以研究修正一下的

**Comment by AlexPresso** [comment]
亲爱的用户，请使用英语语言（我建议您使用ChatGPT进行翻译）

I recently pushed a new version of the patcher and the wrapper, please do the following (as a root user) to update:
- `curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/main/patcher.sh | bash -s -- -a unpatch`
- `curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/main/patcher.sh | bash`

If the subtitles are not recognized, this is not an issue with the patcher or wrapper, but a VideoStation's issue.

Please also provide the required logs so I can analyze further issues (if any).

Thank you

**Comment by AlexPresso** [comment]
Feel free to reopen this issue (or a new one) with all the required informations
