### ISSUE TITLE
[BUG] ffmpeg v4.4.3-48 Change package directory to ffmpeg

### ISSUE THREAD

**Issue by sKyissKy** [AlexPresso/VideoStation-FFMPEG-Patcher#59]
ffmpeg v4.4.3-48 Change package directory to ffmpeg

**Comment by AlexPresso** [comment]
Hi,
Could you give me a little bit more informations please ?

**Comment by Fabian1601** [comment]
Hello Alex,
In the package center is a new ffmpeg update available. In the description it says among other things that the directory has been changed.
Also it should be mentioned that in dsm 7.2 beta ffmpeg 4, ffmpeg 5 and ffmpeg 6 is available for installation in the package center.
Changelog only says Initial release. 

Greetings

**Comment by AlexPresso** [comment]
Hello Fabian,

Thanks for the update. I'll change the Readme a bit, but it won't be possible to use another version than ffmpeg 4.x.x for now because the new packages do not contain the patches for VideoStation's custom args (i.e. `-hls_seek_time`).
