### ISSUE TITLE
[QA] Unable to perform this operation in VideoStation

### ISSUE THREAD

**Issue by lykane1337** [AlexPresso/VideoStation-FFMPEG-Patcher#7]
Hello guys,

I commented the gist [https://gist.github.com/BenjaminPoncet/bbef9edc1d0800528813e75c1669e57e#gistcomment-3808866](url) because I have an issue with VideoStation after running the script. Do not get me wrong. I am very happy that there is hope to get DTS running. Sorry for spamming the gist.

I got this message when I am trying to access the VideoStation-Webinterface:

![Screenshot_01749](https://user-images.githubusercontent.com/64777033/125297174-4cffe300-e327-11eb-83e6-421a580e155a.png)

My Configuration:

>DS118 (rtd1296 (armv8)) 
DSM 7.0-41890
VS 3.0.1-2067
FFMPEG 4.3.2-37
Advanced Media Extensions 1.1.0-0201

I reinstalled VideoStation + Advanced Media Extensions an run your script. I checked the ressources monitor. There is no load on the ressources. CPU 0-5% and the RAM is constantly up to 43%.

Do you have any ideas to solve the problem?

That would be great!

Thank you very much
Kind regards
David

**Comment by AlexPresso** [comment]
Hello,

Do you have any error in `/var/log/packages/VideoStation.log` ?

**Comment by lykane1337** [comment]
I got it running. Here is what I did.

Connecting to the NAS via SSH with "admin" user (some help here)
Use the command sudo -i to switch to root user (same password as for "admin")
Copy / paste the following commands:
# Save VideoStation's ffmpeg
`mv -n /var/packages/VideoStation/target/bin/ffmpeg /var/packages/VideoStation/target/bin/ffmpeg.orig`
# Injecting the script (last revision aka 12)
`wget -O - https://gist.githubusercontent.com/BenjaminPoncet/bbef9edc1d0800528813e75c1669e57e/raw/ffmpeg-wrapper > /var/packages/VideoStation/target/bin/ffmpeg`
# Change ownership and mode of the script
```
chown root:VideoStation /var/packages/VideoStation/target/bin/ffmpeg
chmod 750 /var/packages/VideoStation/target/bin/ffmpeg
chmod u+s /var/packages/VideoStation/target/bin/ffmpeg
```
# Save VideoStation's libsynovte.so
```
cp -n /var/packages/VideoStation/target/lib/libsynovte.so /var/packages/VideoStation/target/lib/libsynovte.so.orig
chown VideoStation:VideoStation /var/packages/VideoStation/target/lib/libsynovte.so.orig
```
# Patch libsynovte.so to authorize DTS, EAC3 and TrueHD
`sed -i -e 's/eac3/3cae/' -e 's/dts/std/' -e 's/truehd/dheurt/' /var/packages/VideoStation/target/lib/libsynovte.so`

# Coping files
```
mv /var/packages/CodecPack/target/bin/ffmpeg27  /var/packages/CodecPack/target/bin/ffmpeg27.orig
mv /var/packages/CodecPack/target/bin/ffmpeg41  /var/packages/CodecPack/target/bin/ffmpeg41.orig
cp /var/packages/VideoStation/target/bin/ffmpeg /var/packages/CodecPack/target/bin/ffmpeg27
cp /var/packages/VideoStation/target/bin/ffmpeg /var/packages/CodecPack/target/bin/ffmpeg41
```

Thank you... Have a nice time!!!

**Comment by AlexPresso** [comment]
Hi,
Sorry for the delay I had a lot of work these days. I'm glad you solved your issue. :)
Thank you for sharing this, I'll update the script based on this.
