### ISSUE TITLE
[QA] can you help make the SA6400 support hardware transcoding

### ISSUE THREAD

**Issue by skill7899** [AlexPresso/VideoStation-FFMPEG-Patcher#73]
now, sa6400 can support 11th gpu (12th and 13th gpu also support but the author is not publicly available )，but the videoStation can not use gpu to hardware code
can you help make the SA6400 support hardware transcoding，
thanks。

https://blog.jim.plus/blog/post/jim/synology-sa6400-with-i915

**Comment by AlexPresso** [comment]
Hey there,
Are you using the wrapper ? or are you asking for a VideoStation's modification ?

**Comment by skill7899** [comment]
> Hey there, Are you using the wrapper ? or are you asking for a VideoStation's modification ?

i using the wrapper

**Comment by AlexPresso** [comment]
Hello @th0ma7
I'm not sure about this issue but I was thinking, is it possible the ffmpeg package not yet supports hardware transcoding for this architecture ?

**Comment by th0ma7** [comment]
When looking at the specs it refers to an AMD CPU https://www.synology.com/en-global/products/SA6400#specs

And the cpu being an AMD EPYC 7272 does not seem to have a gpu neither.

Not much can be done afaik.

**Comment by skill7899** [comment]
> When looking at the specs it refers to an AMD CPU https://www.synology.com/en-global/products/SA6400#specs
> 
> And the cpu being an AMD EPYC 7272 does not seem to have a gpu neither.
> 
> Not much can be done afaik.

but the jim can install 11/12/13 th cpu with sa6400 and the gpu can work will

**Comment by RhythmNz** [comment]
i had same issue

**Comment by RhythmNz** [comment]
root@MoeGen12Nas:~# cat /sys/kernel/debug/dri/0/i915_frequency_info
Video Turbo Mode: yes
HW control enabled: yes
SW control enabled: no
PM IER=0x00000000 IMR=0xffffffff, MASK=0xffffffff
pm_intrmsk_mbz: 0x00000000
GT_PERF_STATUS: 0x00000000
Render p-state ratio: 0
Render p-state VID: 0
Render p-state limit: 0
RPSTAT1: 0xffffffff
RPMODECTL: 0xffffffff
RPINCLIMIT: 0xffffffff
RPDECLIMIT: 0xffffffff
RPNSWREQ: 8517MHz
CAGF: 8517MHz
RP CUR UP EI: 16777215 (13981012500ns)
RP CUR UP: 16777215 (13981012500ns)
RP PREV UP: 16777215 (13981012500ns)
Up threshold: 0%
RP UP EI: -1 (696835650983ns)
RP UP THRESHOLD: -1 (696835650983ns)
RP CUR DOWN EI: 16777215 (13981012500ns)
RP CUR DOWN: 16777215 (13981012500ns)
RP PREV DOWN: 16777215 (13981012500ns)
Down threshold: 0%
RP DOWN EI: -1 (696835650983ns)
RP DOWN THRESHOLD: -1 (696835650983ns)
Lowest (RPN) frequency: 0MHz
Nominal (RP1) frequency: 0MHz
Max non-overclocked (RP0) frequency: 0MHz
Max overclocked frequency: 0MHz
Current freq: 0 MHz
Actual freq: 8517 MHz
Idle freq: 0 MHz
Min freq: 0 MHz
Boost freq: 0 MHz
Max freq: 0 MHz
efficient (RPe) frequency: 0 MHz
Current CD clock frequency: 0 kHz
Max CD clock frequency: 0 kHz
Max pixel clock frequency: 0 kHz

**Comment by AlexPresso** [comment]
Hello @RhythmNz 

I pushed a new version of the wrapper, could you please try it and tell me if you still have issues to use VAAPI:

Please follow these steps to post a new issue report:
- uninstall the patch : `curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/main/patcher.sh | bash -s -- -a unpatch`
- install the new patch `curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/main/patcher.sh | bash -s -- -a patch`
- Play the movie causing issue (keep it playing/loading in background)
- Run the following command: `curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/main/issue-report.sh | bash`
- If you have any issue, copy paste the output to a new gist and place the link here

**Comment by AlexPresso** [comment]
Hello @skill7899 
Could you try to run the above steps to tell me if the latest wrapper is working please ?

**Comment by skill7899** [comment]
> Hello @skill7899 Could you try to run the above steps to tell me if the latest wrapper is working please ?

hi，My device is broken and needs to be repaired before testing can be carried out

**Comment by skill7899** [comment]
> Hello @skill7899 Could you try to run the above steps to tell me if the latest wrapper is working please ?

root@dsm:/volume3/homes/admin# curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/main/issue-report.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2896  100  2896    0     0   4388      0 --:--:-- --:--:-- --:--:--  4387
libva info: VA-API version 1.18.0
libva info: Trying to open /var/packages/ffmpeg/target/lib/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_18
libva info: va_openDriver() returns 0

================ ISSUE REPORT TOOL ================
https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher

System Details.....................................
  DSM Version: 7.2.1 69057-0
  Arch details: Linux dsm 5.10.55+ #69057 SMP Sat Sep 23 21:43:07 CST 2023 x86_64 GNU/Linux synology_epyc7002_sa6400

Package Details....................................
  VideoStation version: 3.1.0-3153
  FFMPEG version (ffmpeg): 4.4.4-49
  CodecPack version: 3.1.0-3005

Patch Details......................................
  Is patched ? yes
  Has gstreamer ? no

FFMPEG VAAPI.......................................
  Trying display: drm
vainfo: VA-API version: 1.18 (libva 2.18.1)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 23.1.6 (3359d2df)
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointFEI
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointFEI
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointFEI
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointFEI
      VAProfileHEVCMain               :	VAEntrypointEncSliceLP
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointEncSliceLP
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile0            :	VAEntrypointEncSliceLP
      VAProfileVP9Profile1            :	VAEntrypointVLD
      VAProfileVP9Profile1            :	VAEntrypointEncSliceLP
      VAProfileVP9Profile2            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointEncSliceLP
      VAProfileVP9Profile3            :	VAEntrypointVLD
      VAProfileVP9Profile3            :	VAEntrypointEncSliceLP
      VAProfileHEVCMain12             :	VAEntrypointVLD
      VAProfileHEVCMain12             :	VAEntrypointEncSlice
      VAProfileHEVCMain422_10         :	VAEntrypointVLD
      VAProfileHEVCMain422_10         :	VAEntrypointEncSlice
      VAProfileHEVCMain422_12         :	VAEntrypointVLD
      VAProfileHEVCMain422_12         :	VAEntrypointEncSlice
      VAProfileHEVCMain444            :	VAEntrypointVLD
      VAProfileHEVCMain444            :	VAEntrypointEncSliceLP
      VAProfileHEVCMain444_10         :	VAEntrypointVLD
      VAProfileHEVCMain444_10         :	VAEntrypointEncSliceLP
      VAProfileHEVCMain444_12         :	VAEntrypointVLD
      VAProfileHEVCSccMain            :	VAEntrypointVLD
      VAProfileHEVCSccMain            :	VAEntrypointEncSliceLP
      VAProfileHEVCSccMain10          :	VAEntrypointVLD
      VAProfileHEVCSccMain10          :	VAEntrypointEncSliceLP
      VAProfileHEVCSccMain444         :	VAEntrypointVLD
      VAProfileHEVCSccMain444         :	VAEntrypointEncSliceLP
      VAProfileAV1Profile0            :	VAEntrypointVLD
      VAProfileHEVCSccMain444_10      :	VAEntrypointVLD
      VAProfileHEVCSccMain444_10      :	VAEntrypointEncSliceLP

CodecPack Details..................................
  Has AAC ? yes
  Has HEVC ? yes

CodecPack target/bin content.......................
total 60
lrwxrwxrwx 1 CodecPack CodecPack    30 Mar 14  2023 ffmpeg33-for-audio -> ../pack/bin/ffmpeg33-for-audio
lrwxrwxrwx 1 CodecPack CodecPack    37 Mar 14  2023 ffmpeg33-for-surveillance -> ../pack/bin/ffmpeg33-for-surveillance
lrwxrwxrwx 1 root      root         44 Aug 14 14:32 ffmpeg41 -> /var/packages/VideoStation/target/bin/ffmpeg
-rwxr-xr-x 1 CodecPack CodecPack 46201 Mar 14  2023 synocodectool

CodecPack target/pack/bin content..................
total 1084
-rwxr-xr-x 1 root root 267312 Mar 24  2023 ffmpeg33-for-audio
-rwxr-xr-x 1 root root 267304 Mar 24  2023 ffmpeg33-for-surveillance
lrwxrwxrwx 1 root root     44 Oct  6 15:13 ffmpeg41 -> /var/packages/VideoStation/target/bin/ffmpeg
-rwxr-xr-x 1 root root 271320 Mar 24  2023 ffmpeg41-for-synoface
-rwxr-xr-x 1 root root 271320 Mar 24  2023 ffmpeg41.orig
-rwxr-xr-x 1 root root  14832 Mar 24  2023 vainfo

CodecPack status...................................
cat: /var/packages/CodecPack/var/codec_requirements.json: No such file or directory
file not exists


GSTInspect last stderr logs........................
tail: cannot open '/tmp/gstinspect*.stderr' for reading: No such file or directory

GSTInspect stderr.prev logs........................
cat: '/tmp/gstinspect*.stderr.prev': No such file or directory

GSTLaunch last stderr logs.........................
tail: cannot open '/tmp/gstlaunch*.stderr' for reading: No such file or directory

GSTLaunch stderr.prev logs.........................
cat: '/tmp/gstlaunch*.stderr.prev': No such file or directory

FFMPEG head logs...................................
head: cannot open '/tmp/ffmpeg*.stderr' for reading: No such file or directory

FFMPEG last stderr logs............................
tail: cannot open '/tmp/ffmpeg*.stderr' for reading: No such file or directory

FFMPEG prev logs...................................
cat: '/tmp/ffmpeg*.stderr.prev': No such file or directory

i test play mkv vedio，it not work

**Comment by skill7899** [comment]
Press [q] to stop, [?] for help
x264 [error]: baseline profile doesn't support a bit depth of 10
[libx264 @ 0x55d79f2e8d00] Error setting profile baseline.
[libx264 @ 0x55d79f2e8d00] Possible profiles: baseline main high high10 high422 high444
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
[libfdk_aac @ 0x55d79f2ea280] 2 frames left in the queue on closing
Conversion failed!
[2023-10-06 15:19:38] [ERROR] An error occurred

[2023-10-06 15:19:38] [INFO] ========================================[end ffmpeg 27954]

@AlexPresso  no work will

**Comment by AlexPresso** [comment]
Hi @skill7899 
I recently fixed a bug with the pixel format of MPEG4 high10, it's not related to hardware transcoding but could you please try it anyway ?

**Comment by skill7899** [comment]
root@dsm:~# curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/main/issue-report.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2896  100  2896    0     0   2016      0  0:00:01  0:00:01 --:--:--  2016
libva info: VA-API version 1.18.0
libva info: Trying to open /var/packages/ffmpeg/target/lib/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_18
libva info: va_openDriver() returns 0

================ ISSUE REPORT TOOL ================
https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher

System Details.....................................
  DSM Version: 7.2.1 69057-1
  Arch details: Linux dsm 5.10.55+ #69057 SMP Fri Oct 6 11:28:38 CST 2023 x86_64 GNU/Linux synology_epyc7002_sa6400

Package Details....................................
  VideoStation version: 3.1.0-3153
  FFMPEG version (ffmpeg): 4.4.4-49
  CodecPack version: 3.1.0-3005

Patch Details......................................
  Is patched ? yes
  Has gstreamer ? no

FFMPEG VAAPI.......................................
  Trying display: drm
vainfo: VA-API version: 1.18 (libva 2.18.1)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 23.1.6 (3359d2df)
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointFEI
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointFEI
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointFEI
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointFEI
      VAProfileHEVCMain               :	VAEntrypointEncSliceLP
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointEncSliceLP
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile0            :	VAEntrypointEncSliceLP
      VAProfileVP9Profile1            :	VAEntrypointVLD
      VAProfileVP9Profile1            :	VAEntrypointEncSliceLP
      VAProfileVP9Profile2            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointEncSliceLP
      VAProfileVP9Profile3            :	VAEntrypointVLD
      VAProfileVP9Profile3            :	VAEntrypointEncSliceLP
      VAProfileHEVCMain12             :	VAEntrypointVLD
      VAProfileHEVCMain12             :	VAEntrypointEncSlice
      VAProfileHEVCMain422_10         :	VAEntrypointVLD
      VAProfileHEVCMain422_10         :	VAEntrypointEncSlice
      VAProfileHEVCMain422_12         :	VAEntrypointVLD
      VAProfileHEVCMain422_12         :	VAEntrypointEncSlice
      VAProfileHEVCMain444            :	VAEntrypointVLD
      VAProfileHEVCMain444            :	VAEntrypointEncSliceLP
      VAProfileHEVCMain444_10         :	VAEntrypointVLD
      VAProfileHEVCMain444_10         :	VAEntrypointEncSliceLP
      VAProfileHEVCMain444_12         :	VAEntrypointVLD
      VAProfileHEVCSccMain            :	VAEntrypointVLD
      VAProfileHEVCSccMain            :	VAEntrypointEncSliceLP
      VAProfileHEVCSccMain10          :	VAEntrypointVLD
      VAProfileHEVCSccMain10          :	VAEntrypointEncSliceLP
      VAProfileHEVCSccMain444         :	VAEntrypointVLD
      VAProfileHEVCSccMain444         :	VAEntrypointEncSliceLP
      VAProfileAV1Profile0            :	VAEntrypointVLD
      VAProfileHEVCSccMain444_10      :	VAEntrypointVLD
      VAProfileHEVCSccMain444_10      :	VAEntrypointEncSliceLP

CodecPack Details..................................
  Has AAC ? yes
  Has HEVC ? yes

CodecPack target/bin content.......................
total 60
lrwxrwxrwx 1 CodecPack CodecPack    30 Mar 14  2023 ffmpeg33-for-audio -> ../pack/bin/ffmpeg33-for-audio
lrwxrwxrwx 1 CodecPack CodecPack    37 Mar 14  2023 ffmpeg33-for-surveillance -> ../pack/bin/ffmpeg33-for-surveillance
lrwxrwxrwx 1 root      root         44 Aug 14 14:32 ffmpeg41 -> /var/packages/VideoStation/target/bin/ffmpeg
-rwxr-xr-x 1 CodecPack CodecPack 46201 Mar 14  2023 synocodectool

CodecPack target/pack/bin content..................
total 1084
-rwxr-xr-x 1 root root 267312 Mar 24  2023 ffmpeg33-for-audio
-rwxr-xr-x 1 root root 267304 Mar 24  2023 ffmpeg33-for-surveillance
lrwxrwxrwx 1 root root     44 Oct 21 23:12 ffmpeg41 -> /var/packages/VideoStation/target/bin/ffmpeg
-rwxr-xr-x 1 root root 271320 Mar 24  2023 ffmpeg41-for-synoface
-rwxr-xr-x 1 root root 271320 Mar 24  2023 ffmpeg41.orig
-rwxr-xr-x 1 root root  14832 Mar 24  2023 vainfo

CodecPack status...................................
cat: /var/packages/CodecPack/var/codec_requirements.json: No such file or directory
file not exists


GSTInspect last stderr logs........................
tail: cannot open '/tmp/gstinspect*.stderr' for reading: No such file or directory

GSTInspect stderr.prev logs........................
cat: '/tmp/gstinspect*.stderr.prev': No such file or directory

GSTLaunch last stderr logs.........................
tail: cannot open '/tmp/gstlaunch*.stderr' for reading: No such file or directory

GSTLaunch stderr.prev logs.........................
cat: '/tmp/gstlaunch*.stderr.prev': No such file or directory

FFMPEG head logs...................................

[2023-10-21 23:13:22] [INFO] ========================================[start ffmpeg 26998]
[2023-10-21 23:13:22] [INFO] DEFAULT ARGS: -ss 0.000 -i /volume3/video/stata/aria2-downloads/Justice.League.Dark.Apokolips.War.2020.2160p.BluRay.x265.10bit.SDR.DTS-HD.MA.5.1-SWTYBLZ.mkv -threads 0 -vcodec libx264 -vsync 2 -preset superfast -vprofile baseline -level 30 -s 480x360 -vb 720000 -r 15 -acodec libmp3lame -ab 64k -ac 2 -f ssegment -pix_fmt yuv420p -segment_format mpegts -segment_list_type m3u8 -hls_seek_time 0 -segment_time 5 -segment_time_delta 0.000 -segment_start_number 00000 -avoid_negative_ts 0 -break_non_keyframes 1 -max_muxing_queue_size 1024 -map 0:0 -map 0:1 /tmp/VideoStation/HLS/3b4679cd53b708034ac64040488ca787_CljIpyRL/slice-%05d.ts
[2023-10-21 23:13:22] [INFO] UPDATED ARGS: -ss 0.000 -i /volume3/video/stata/aria2-downloads/Justice.League.Dark.Apokolips.War.2020.2160p.BluRay.x265.10bit.SDR.DTS-HD.MA.5.1-SWTYBLZ.mkv -threads 0 -vcodec libx264 -vsync 2 -preset superfast -vprofile baseline -level 30 -s 480x360 -vb 720000 -acodec libfdk_aac -ab 64k -ac 2 -f ssegment -pix_fmt yuv420p -segment_format mpegts -segment_list_type m3u8 -hls_seek_time 0 -segment_time 5 -segment_time_delta 0.000 -segment_start_number 00000 -avoid_negative_ts 0 -break_non_keyframes 1 -max_muxing_queue_size 1024 -map 0:0 -map 0:1 /tmp/VideoStation/HLS/3b4679cd53b708034ac64040488ca787_CljIpyRL/slice-%05d.ts
[2023-10-21 23:13:22] [INFO] Trying with VideoStation's ffmpeg with fixed args...
ffmpeg version 4.1.8 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 12.2.0 (GCC)
  configuration: --prefix=/usr/pkg --incdir='${prefix}/include/ffmpeg' --arch=i686 --pkg-config=/usr/bin/pkg-config --target-os=linux --cross-prefix=/usr/local/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu- --enable-cross-compile --enable-optimizations --enable-pic --enable-gpl --enable-version3 --enable-nonfree --enable-encoders --enable-pthreads --disable-protocols --disable-protocol=rtp --enable-protocol=file --enable-protocol=http --enable-protocol=pipe --disable-muxer=image2 --disable-muxer=image2pipe --disable-swscale-alpha --disable-ffplay --disable-doc --disable-devices --disable-bzlib --disable-altivec --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libmp3lame --disable-decoder=amrnb --disable-encoder=zmbv --disable-encoder=dca --disable-decoder=dca --disable-encoder=ac3 --disable-encoder=ac3_fixed --disable-encoder=eac3 --disable-decoder=eac3 --disable-encoder=truehd --disable-decoder=truehd --disable-encoder=aac --disable-decoder=aac --disable-decoder=aac_fixed --disable-encoder=hevc_vaapi --disable-decoder=hevc --disable-muxer=hevc --disable-demuxer=hevc --disable-parser=hevc --disable-bsf=hevc_mp4toannexb --x86asmexe=yasm --extra-cflags=-I/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/pkg/include --extra-ldflags=-L/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/pkg/lib --cc=/usr/local/x86_64-pc-linux-gnu/bin/ccache/x86_64-pc-linux-gnu-wrap-gcc --enable-shared --disable-static --enable-vaapi --enable-yasm --enable-libx264 --enable-encoder=h264_vaapi --enable-encoder=libx264
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100

FFMPEG last stderr logs............................
    Metadata:
      title           : Justice.League.Dark.Apokolips.War.2020.2160p.BluRay.x265.10bit.SDR.DTS-HD.MA.5.1-SWTYBLZ
      BPS-eng         : 2320416
      DURATION-eng    : 01:30:10.667000000
      NUMBER_OF_FRAMES-eng: 507250
      NUMBER_OF_BYTES-eng: 1569375028
      SOURCE_ID-eng   : 001100
      _STATISTICS_WRITING_APP-eng: mkvmerge v46.0.0 ('No Deeper Escape') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-05-22 14:26:34
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
      encoder         : Lavc58.134.100 libfdk_aac
[stream_segment,ssegment @ 0x55931be0db40] Opening '/tmp/VideoStation/HLS/3b4679cd53b708034ac64040488ca787_CljIpyRL/slice-00001.ts' for writing
[stream_segment,ssegment @ 0x55931be0db40] Opening '/tmp/VideoStation/HLS/3b4679cd53b708034ac64040488ca787_CljIpyRL/slice-00002.ts' for writing
[stream_segment,ssegment @ 0x55931be0db40] Opening '/tmp/VideoStation/HLS/3b4679cd53b708034ac64040488ca787_CljIpyRL/slice-00003.ts' for writing
[stream_segment,ssegment @ 0x55931be0db40] Opening '/tmp/VideoStation/HLS/3b4679cd53b708034ac64040488ca787_CljIpyRL/slice-00004.ts' for writing
[stream_segment,ssegment @ 0x55931be0db40] Opening '/tmp/VideoStation/HLS/3b4679cd53b708034ac64040488ca787_CljIpyRL/slice-00005.ts' for writing
[stream_segment,ssegment @ 0x55931be0db40] Opening '/tmp/VideoStation/HLS/3b4679cd53b708034ac64040488ca787_CljIpyRL/slice-00006.ts' for writing
[stream_segment,ssegment @ 0x55931be0db40] Opening '/tmp/VideoStation/HLS/3b4679cd53b708034ac64040488ca787_CljIpyRL/slice-00007.ts' for writing
[stream_segment,ssegment @ 0x55931be0db40] Opening '/tmp/VideoStation/HLS/3b4679cd53b708034ac64040488ca787_CljIpyRL/slice-00008.ts' for writing
[stream_segment,ssegment @ 0x55931be0db40] Opening '/tmp/VideoStation/HLS/3b4679cd53b708034ac64040488ca787_CljIpyRL/slice-00009.ts' for writing
[stream_segment,ssegment @ 0x55931be0db40] Opening '/tmp/VideoStation/HLS/3b4679cd53b708034ac64040488ca787_CljIpyRL/slice-00010.ts' for writing
frame= 1286 fps= 51 q=13.0 size=N/A time=00:00:54.01 bitrate=N/A speed=2.13x
FFMPEG prev logs...................................
cat: '/tmp/ffmpeg*.stderr.prev': No such file or directory

@AlexPresso

**Comment by AlexPresso** [comment]
Aaah perfect it's working :)

**Comment by skill7899** [comment]
> Aaah perfect it's working :)

but cpu high use，look like use cpu transcoding

**Comment by AlexPresso** [comment]
Yes, I can try to have a look at it, but it's not a problem with the wrapper

**Comment by skill7899** [comment]
> Yes, I can try to have a look at it, but it's not a problem with the wrapper

I checked the logs above and found that the parameters of ffmpeg do not have any information related to GPU

**Comment by AlexPresso** [comment]
Yes, the parameters are generated by VideoStation, the only modifications made on the parameters are to fix issues with scale_vaapi

Everything else is default so maybe VideoStation or ffmpeg is not detecting Hardware acceleration on your NAS
