### ISSUE TITLE
[BUG] Movies with AAC codec in system without AAC support doesn't works

### ISSUE THREAD

**Issue by REDoxONA** [AlexPresso/VideoStation-FFMPEG-Patcher#82]
Videos with AAC audio codec in system whitout AAC enabled, doesn't works. I have another NAS without AAC license and with your wrapper I can't see them.
![image](https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/assets/141912318/92185034-070e-4678-9287-21c8a9631144)

![image](https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/assets/141912318/cc062fae-5688-46ec-809b-31698b79c24c)

Regards.

**Comment by ner00** [comment]
If AME isn't using a valid license or if it isn't properly patched this is normal. The wrapper does not enable HEVC nor AAC, these must be provided by AME either legally or patched.

**Comment by REDoxONA** [comment]
My AME is legally patched as you can see here. I can't see movies with AAC codec.

**Comment by ner00** [comment]
> My AME is legally patched as you can see here. I can't see movies with AAC codec.

Mine is patched and it shows 2 green checkmarks, one for HEVC and another for AAC, but that may be unrelated.

**Comment by AlexPresso** [comment]
Hello @REDoxONA 
Thank you for your issue, I will investigate it, could you please provide your hardware informations version of DSM, VideoStation and CodecPack (as in the issue template) please

**Comment by AlexPresso** [comment]
I need more details to investigate this issue, please open a ssh terminal to your NAS with root access and paste the output of the following command:
`curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/cleaning_improvements/issue-report.sh | bash`

**Comment by AlexPresso** [comment]
Looking for people without AAC support to test it
