### ISSUE TITLE
Problems after updating to DSM 7.0-41890 - Videos with DTS Audio don't play in VideoStation Web Interface anymore

### ISSUE THREAD

**Issue by justfreaky0815** [AlexPresso/VideoStation-FFMPEG-Patcher#9]
After updating my DSM some days ago to the newest version (as mentioned above) I'm not able anymore to play videos with DTS audio in the VideoStation Web Interface anymore.

Negative/main side effect is that Videos with DTS audio track now are very often buffering when streaming from outside my network like they did also when no ffmpeg was installed and your patch hasn't been  applied - before DSM update it worked like a charm.

Patching again has only the effect that the video does not stop with a shown error but simply does not start (in Web-Interface)

Hope I described it as good as possible...

Any ideas?

My System:

DS-218+
DSM 7.0-41890
Video Station 3.0.1-2067
ffmpeg 4.3.2-37
Advanced media extensions  1.1.1-0202

**Comment by AlexPresso** [comment]
Hey there,
Yes, I still haven't updated to DSM 7.0. The patcher may need some improvements to work with DSM 7.0. I'll test it and get back to you.

**Comment by Pythonix** [comment]
> Hey there,
> Yes, I still haven't updated to DSM 7.0. The patcher may need some improvements to work with DSM 7.0. I'll test it and get back to you.

I have been able to use your wrapper under DSM7 without any problems. I only had to change the name `ffmpeg33` to `ffmpeg41`.

**Comment by AlexPresso** [comment]
> > Hey there,
> > Yes, I still haven't updated to DSM 7.0. The patcher may need some improvements to work with DSM 7.0. I'll test it and get back to you.
> 
> I have been able to use your wrapper under DSM7 without any problems. I only had to change the name `ffmpeg33` to `ffmpeg41`.

Yes, it's randomly working on some architectures, but unfortunately not anymore on my DS218Play (and probably others armv8)
 I'll patch the script to handle `ffmpeg*` files in CodecPack.

**Comment by AlexPresso** [comment]
I just pushed some fixes + improvements to the patcher ( #10 ) could you please try to:
- uninstall VideoStation (keep library)
- uninstall Advanced Media Extensions
- reinstall VideoStation (it should ask to install Advanced Media Extensions too, click "yes")
- follow the instructions on the repository readme (main branch)
