### ISSUE TITLE
[BUG] offline transcoding fails after latest script update

### ISSUE THREAD

**Issue by Fabian1601** [AlexPresso/VideoStation-FFMPEG-Patcher#90]
Hello Alex,
after the last script update 2 weeks ago every movie is played but the offline transcoding is not possible. I tried it with ffmpeg v4 and v6, it comes the same error. also in your error report script

"[scale_vaapi @ 0x5647b9fb2c80] [Eval @ 0x7ffea2727d70] Undefined constant or missing '(' in 'format=nv12|vaapi'
    Last message repeated 1 times
[scale_vaapi @ 0x5647b9fb2c80] Error when evaluating the expression 'format=nv12|vaapi'."

my system:
- ds1520+
- dsm 7.2-64570 update 3
- vs 3.1.0-3153
- ams 3.1.0-3005
- ffmpeg 6.0-2
- ffmpeg 4.4.4-49

https://gist.github.com/Fabian1601/0dff6091cfe03781f579efeedd79737b

**Comment by AlexPresso** [comment]
Hello Fabian,

Thanks for your issue, yes you are right, I'll fix this today or tomorrow, sorry for the bug

**Comment by Fabian1601** [comment]
Hello Alex,

now everything is working like a charm, thanks :-)

**Comment by AlexPresso** [comment]
Thanks to you, I'm glad everything working again :)
