### ISSUE TITLE
[QA] no transcoding on old samsung tv with ds video app

### ISSUE THREAD

**Issue by Fabian1601** [AlexPresso/VideoStation-FFMPEG-Patcher#92]
Hello Alex,
I also have an old Samsung TV at home, next to my Android TV where DSVideos now runs without any problems thanks to your script. Although it also has the DSVideos app, it unfortunately has a very old version 10.7-081. When I transcode a movie offline, the TV plays it perfectly. However, when I try to play an H265 film, it doesn’t play and says that the format is not supported. Shouldn’t it be able to convert it on the fly?

Thanks

**Comment by AlexPresso** [comment]
Hm... Yes, the smart-tv DSVideo app is having a little bit different behavior (You can check "Case 3" in #88) it's possible your TV doesn't support H.265 at all

**Comment by AlexPresso** [comment]
I'm closing this issue, but feel free to open it again if you have more questions
