### ISSUE TITLE
[BUG] Stop playing some formats that played before patching

### ISSUE THREAD

**Issue by dmoskovchenko** [AlexPresso/VideoStation-FFMPEG-Patcher#95]
**Provide System Details**
Model: DS220+
DSM version: DSM 7.2-64570 Update 3
Video Station: 3.1.0-3153
FFmpeg 4 /5 /6 from Community centre
Logs: https://gist.github.com/dmoskovchenko/2c2a719e4d9c0ab98fbbd13c43aa3955

**Describe the bug**
After patching some videos stop playing, 
![image](https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/assets/51199286/c70c20da-9173-475f-ae51-9fbd813312be)

If I tried  _-s -- -a unpatch_  this videos begin playing. 

I need a patch to play videos with  eac3  sound. After patching, videos with eac3 sound working well.

Please help me with this issue.

**Comment by AlexPresso** [comment]
Hello,

I'll have a look at it as soon as I can

**Comment by AlexPresso** [comment]
Hello @dmoskovchenko 

I made a fix attempt in the linked PR, could you try to use the following procedure to test it please:

- uninstall the patch : `curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/fix_scale_vaapi/patcher.sh | bash -s -- -a unpatch`
- install the new patch `curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/fix_scale_vaapi/patcher.sh | bash -s -- -a patch -b fix_scale_vaapi`

If you still have an issue please run the issue-report tool and post the result here again

**Comment by dmoskovchenko** [comment]
Hello, first of all I want to thank you  for your work.
I have treid ^
![image](https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/assets/51199286/3c23bb7a-9848-4f9e-bd0b-ac9a95960246)

No chages for me 

Here is log file: https://gist.github.com/dmoskovchenko/c8f058d6149bbf83341ac551b14ca1a0

**Comment by dmoskovchenko** [comment]
AAfter patching on this link the bideo picture is strage:
![image](https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/assets/51199286/b97967ca-bc4f-48ee-b113-9e48d9946af6)

and if I do unpatch video picture format  became normal but without eac3(( :  
![image](https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/assets/51199286/e85cc06a-f14b-4e32-8f03-7a73d7197b64)

**Comment by AlexPresso** [comment]
My bad, I inverted the `w` and `h`, could you please unpatch and repatch using the same above commands

**Comment by dmoskovchenko** [comment]
> After patching on this link(branch) the video picture is strange: ![image](https://user-images.githubusercontent.com/51199286/271851778-b97967ca-bc4f-48ee-b113-9e48d9946af6.png)
> 
> and if I do unpatch video picture format became normal but without eac3(( : ![image](https://user-images.githubusercontent.com/51199286/271851822-e85cc06a-f14b-4e32-8f03-7a73d7197b64.png)

this part is fixed, but in general the videos rhat plays in unpatched mode still has problem with playing

 Here is log: https://gist.github.com/dmoskovchenko/ce76407af830f24ef1257a18c123f64a

**Comment by AlexPresso** [comment]
Thank you for the feedback
I tried to re-add the vaapi to the filter chain, could you please unpatch/repatch using the same commands and give it a try

Could you also give me the ouput of the following command:
- `vainfo`
- (only in case the first one didn't work) `/bin/vainfo`

**Comment by dmoskovchenko** [comment]
Here is it: https://gist.github.com/dmoskovchenko/4d87abe48fa9fa470ac94618b0069366

**Comment by AlexPresso** [comment]
Do you have any output if running `/var/packages/VideoStation/target/bin/vainfo` ?
Unfortunately, I can't test it by myself because my NAS is not having an Intel CPU and so doesn't have VAAPI

**Comment by dmoskovchenko** [comment]
Here is /var/packages/VideoStation/target/bin/vainfo
[vainfo.zip](https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/files/12778223/vainfo.zip)

**Comment by AlexPresso** [comment]
Thank you for the report :)

Hello @th0ma7, I hope you're doing well
By any chance, do you have an idea why the PO is able to play the video with default `ffmpeg` but not with the SC's `ffmpeg` ? Could it be possible the SC's `ffmpeg` is missing the MPEG4 Advanced Simple profile ?

**Comment by th0ma7** [comment]
@AlexPresso the following should provide the list of decoders available, which in turn depends of the platform and ffmpeg version in usage:
```
$ /usr/local/bin/ffmpeg6 -hide_banner -decoders | grep -i mpeg
 VFS..D ffv1                 FFmpeg video codec #1
 VF..BD ffvhuff              Huffyuv FFmpeg variant
 VFS..D h264                 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
 V....D libopenh264          OpenH264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (codec h264)
 V.S.BD mpeg1video           MPEG-1 video
 V..... mpeg1_v4l2m2m        V4L2 mem2mem MPEG1 decoder wrapper (codec mpeg1video)
 V.S.BD mpeg2video           MPEG-2 video
 V.S.BD mpegvideo            MPEG-1 video (codec mpeg2video)
 V..... mpeg2_v4l2m2m        V4L2 mem2mem MPEG2 decoder wrapper (codec mpeg2video)
 V....D mpeg2_qsv            MPEG2VIDEO video (Intel Quick Sync Video acceleration) (codec mpeg2video)
 VF..BD mpeg4                MPEG-4 part 2
 V..... mpeg4_v4l2m2m        V4L2 mem2mem MPEG4 decoder wrapper (codec mpeg4)
 V...BD msmpeg4v1            MPEG-4 part 2 Microsoft variant version 1
 V...BD msmpeg4v2            MPEG-4 part 2 Microsoft variant version 2
 V...BD msmpeg4              MPEG-4 part 2 Microsoft variant version 3 (codec msmpeg4v3)
 A....D mp1                  MP1 (MPEG audio layer 1)
 A....D mp1float             MP1 (MPEG audio layer 1) (codec mp1)
 A....D mp2                  MP2 (MPEG audio layer 2)
 A....D mp2float             MP2 (MPEG audio layer 2) (codec mp2)
 A....D mp3float             MP3 (MPEG audio layer 3) (codec mp3)
 A....D mp3                  MP3 (MPEG audio layer 3)
 A....D mp3adufloat          ADU (Application Data Unit) MP3 (MPEG audio layer 3) (codec mp3adu)
 A....D mp3adu               ADU (Application Data Unit) MP3 (MPEG audio layer 3)
 A....D als                  MPEG-4 Audio Lossless Coding (ALS) (codec mp4als)
```
And to get more details on a specific decoder:
```
$ /usr/local/bin/ffmpeg6 -hide_banner -h decoder=mpeg4
Decoder mpeg4 [MPEG-4 part 2]:
    General capabilities: horizband dr1 delay threads 
    Threading capabilities: frame
    Supported hardware devices: vaapi 
    Supported pixel formats: vaapi yuv420p
MPEG4 Video Decoder AVOptions:
```
Considering DS220+ is a geminilake (x64) pretty much everything should be enabled including vaapi acceleration.

**Comment by dmoskovchenko** [comment]
Hello, @th0ma7  thx for your answer. Here is New logs: https://gist.github.com/dmoskovchenko/4e5f79795ac0b0da7541e0e7dc1bd0ac  with the commands that you provided.

For this time I found another resource with wrapper patcher(as a work around) that helps me to solve the issue , now all formats are played well.

I still want to understand if this problem is only mine and still want to help @AlexPresso  to enchance his project  :)

**Comment by AlexPresso** [comment]
Thank you for the feedback @th0ma7 :)

And thank to you @dmoskovchenko for your will to help and for giving informations from the commands, it's highly appreciated 👌.
But the one you used are for `ffmpeg6` and I see from the issue-report that your patch configuration is using `ffmpeg4`, could you give me the output of the following commands for ffmpeg4 please (needs `sudo`): 

- `/var/packages/ffmpeg/target/bin/ffmpeg4 -hide_banner -decoders | grep -i mpeg`
- `sudo su -s /bin/bash sc-ffmpeg -c '/var/packages/ffmpeg/target/bin/vainfo'`
- and also this one to see what are the capabilities of VideoStation's default ffmpeg: `/var/packages/VideoStation/target/bin/ffmpeg.orig -hide_banner -decoders | grep -i mpeg`

To give some explainations about my thoughts:
The reason why it's working with the other wrapper you're using, is because the other wrapper is in first case, trying to run the transcoding with the default VideoStation's ffmpeg. My wrapper is only using the SynoCommunity's ffmpeg. I decided to do it this way because the SC ffmpeg is having way more capabilities and is containing latest ffmpeg optimizations.

**Comment by AlexPresso** [comment]
Hello @dmoskovchenko 

If you have time, I made a new patch to try my theory about the previous comment, if you are okay to try it here are the steps:

- uninstall the other patch (the two patches are incompatible)
- uninstall the patch : `curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/multitry_ffmpeg/patcher.sh | bash -s -- -a unpatch`
- install the new patch `curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/multitry_ffmpeg/patcher.sh | bash -s -- -a patch -b multitry_ffmpeg`

If you still have an issue please run the issue-report tool and post the result here again

**Comment by dmoskovchenko** [comment]
Hello, I have tried new solution and at once everything works fine for me now. 
 Great job.
I will stay on your solution, it is nice to be intouch with developer in resolving an issue. 
I wat to thank you one more time for your work .

**Comment by dmoskovchenko** [comment]
Fixed

**Comment by AlexPresso** [comment]
Thank you very much for testing :)
I'm glad everything working fine, but could you please just give me the output of the commands in the following comment so I can have a deep understanding of what was not working fine in the first try please: https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/issues/95#issuecomment-1745398234

**Comment by dmoskovchenko** [comment]
Here are logs: https://gist.github.com/dmoskovchenko/cea0724f701ea6f7f10192297f90acb0

**Comment by AlexPresso** [comment]
Thank you :)

**Comment by Gargaj** [comment]
Getting the same issue with some HEVC files - work fine before patching, don't work at all after.
Log: https://pastebin.com/raw/aWjq4cej

**Comment by AlexPresso** [comment]
Hi @Gargaj 
Thank you for the report, could you provide me the video file so I can do some tests locally please ?

**Comment by Gargaj** [comment]
Any HEVC file will do that has `yuv420p10le` pixel format:
https://www.dropbox.com/scl/fi/0p81fmldvrvxzip6jlv0r/Big_Buck_Bunny_1080_10s_30MB-yuv420p10le.mp4?rlkey=rw96xaib9v0t0v97l3yumvn0v&dl=0

**Comment by AlexPresso** [comment]
I made a fix attempt in the linked PR (#102) , could you try to use the following procedure to test it please:

- uninstall the patch : `curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/fix_pixfmt/patcher.sh | bash -s -- -a unpatch`
- install the new patch `curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/fix_pixfmt/patcher.sh | bash -s -- -a patch -b fix_pixfmt`

If you still have an issue please run the issue-report tool and post the result here again

**Comment by Gargaj** [comment]
Seems to be working on the few I tried! If I run into issues I'll come back.

**Comment by AlexPresso** [comment]
Alright, thank you for testing :)
